<?php

namespace Database\Seeders;

use App\Models\EmpresaContratada;
use Illuminate\Database\Seeder;

class EmpresaContratadaSeeder extends Seeder
{
    public function run(): void
    {
        $empresas = [
            [
                'nome'            => 'Elétrica Paulista Ltda',
                'cnpj'            => '12.345.678/0001-90',
                'email'           => 'contato@eletricapaulista.com.br',
                'responsavel'     => 'Carlos Mendes',
                'telefone'        => '(41) 98877-1111',
                'numero_contrato' => 'CTR-2024-001',
                'cep'             => '87538-000',
                'logradouro'      => 'Rua das Indústrias',
                'numero'          => '300',
                'complemento'     => null,
                'bairro'          => 'Distrito Industrial',
                'cidade'          => 'Perobal',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'Hidro Serviços Paraná ME',
                'cnpj'            => '23.456.789/0001-01',
                'email'           => 'hidro@hidroservicos.com.br',
                'responsavel'     => 'Ana Souza',
                'telefone'        => '(41) 98877-2222',
                'numero_contrato' => 'CTR-2024-002',
                'cep'             => '87538-010',
                'logradouro'      => 'Avenida Comercial',
                'numero'          => '88',
                'complemento'     => 'Sala 2',
                'bairro'          => 'Centro',
                'cidade'          => 'Perobal',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'Construmax Reformas e Pinturas',
                'cnpj'            => '34.567.890/0001-12',
                'email'           => 'reformas@construmax.com.br',
                'responsavel'     => 'Roberto Lima',
                'telefone'        => '(41) 98877-3333',
                'numero_contrato' => 'CTR-2024-003',
                'cep'             => '87538-020',
                'logradouro'      => 'Rua dos Trabalhadores',
                'numero'          => '55',
                'complemento'     => null,
                'bairro'          => 'Jardim Novo',
                'cidade'          => 'Perobal',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'TelhaFix Coberturas e Calhas',
                'cnpj'            => '45.678.901/0001-23',
                'email'           => 'contato@telhafix.com.br',
                'responsavel'     => 'Marcos Oliveira',
                'telefone'        => '(41) 98877-4444',
                'numero_contrato' => 'CTR-2024-004',
                'cep'             => '87538-030',
                'logradouro'      => 'Rua das Acácias',
                'numero'          => '210',
                'complemento'     => null,
                'bairro'          => 'Jardim das Flores',
                'cidade'          => 'Perobal',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'ServiTech Instalações Elétricas',
                'cnpj'            => '56.789.012/0001-34',
                'email'           => 'eletrica@servitech.com.br',
                'responsavel'     => 'Fernanda Costa',
                'telefone'        => '(41) 98877-5555',
                'numero_contrato' => 'CTR-2024-005',
                'cep'             => '87538-040',
                'logradouro'      => 'Rua Sete de Setembro',
                'numero'          => '77',
                'complemento'     => null,
                'bairro'          => 'Vila Nova',
                'cidade'          => 'Perobal',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'Predial Norte Manutenções',
                'cnpj'            => '67.890.123/0001-45',
                'email'           => 'contato@predialnorte.com.br',
                'responsavel'     => 'João Ferreira',
                'telefone'        => '(41) 98877-6666',
                'numero_contrato' => 'CTR-2024-006',
                'cep'             => '87538-050',
                'logradouro'      => 'Avenida Independência',
                'numero'          => '500',
                'complemento'     => 'Bloco B',
                'bairro'          => 'Centro',
                'cidade'          => 'Umuarama',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'AlvenTech Construções Ltda',
                'cnpj'            => '78.901.234/0001-56',
                'email'           => 'obras@alventech.com.br',
                'responsavel'     => 'Paulo Ramos',
                'telefone'        => '(44) 98877-7777',
                'numero_contrato' => 'CTR-2024-007',
                'cep'             => '87501-000',
                'logradouro'      => 'Rua Maringá',
                'numero'          => '1200',
                'complemento'     => null,
                'bairro'          => 'Zona I',
                'cidade'          => 'Umuarama',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'AquaFix Hidráulica e Saneamento',
                'cnpj'            => '89.012.345/0001-67',
                'email'           => 'aquafix@hidraulica.com.br',
                'responsavel'     => 'Silvia Martins',
                'telefone'        => '(44) 98877-8888',
                'numero_contrato' => 'CTR-2024-008',
                'cep'             => '87502-000',
                'logradouro'      => 'Rua das Palmeiras',
                'numero'          => '340',
                'complemento'     => null,
                'bairro'          => 'Jardim Palmeiras',
                'cidade'          => 'Umuarama',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'VerdeClean Serviços Gerais',
                'cnpj'            => '90.123.456/0001-78',
                'email'           => 'verde@verdeclean.com.br',
                'responsavel'     => 'Tatiane Rocha',
                'telefone'        => '(44) 98877-9999',
                'numero_contrato' => 'CTR-2024-009',
                'cep'             => '87503-000',
                'logradouro'      => 'Avenida Tiradentes',
                'numero'          => '90',
                'complemento'     => null,
                'bairro'          => 'São Cristóvão',
                'cidade'          => 'Umuarama',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
            [
                'nome'            => 'MetalFix Serralheria e Estruturas',
                'cnpj'            => '01.234.567/0001-89',
                'email'           => 'metalfix@estruturas.com.br',
                'responsavel'     => 'Diego Alves',
                'telefone'        => '(44) 98877-0000',
                'numero_contrato' => 'CTR-2024-010',
                'cep'             => '87504-000',
                'logradouro'      => 'Rua Pioneiros',
                'numero'          => '15',
                'complemento'     => null,
                'bairro'          => 'Distrito Industrial',
                'cidade'          => 'Umuarama',
                'estado'          => 'PR',
                'ativo'           => true,
                'alterado_por'    => 'Sistema',
            ],
        ];

        foreach ($empresas as $empresa) {
            EmpresaContratada::firstOrCreate(['cnpj' => $empresa['cnpj']], $empresa);
        }

        $this->command->info('✔ 10 empresas contratadas criadas.');
    }
}