<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItensSeeder extends Seeder
{
    public function run(): void
    {
        $itens = [
            // ─── CEREAIS E DERIVADOS ────────────────────────────────────
            ['nome' => 'Arroz, integral, cozido', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz, integral, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz, tipo 1, cozido', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz, tipo 1, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz, tipo 2, cozido', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz, tipo 2, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Aveia, flocos, crua', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, doce, maisena', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, doce, recheado com chocolate', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, doce, recheado com morango', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, doce, wafer, recheado de chocolate', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, doce, wafer, recheado de morango', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, salgado, cream cracker', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo, mistura para', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo, pronto, aipim', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo, pronto, chocolate', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo, pronto, coco', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo, pronto, milho', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Canjica, branca, crua', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Canjica, com leite integral', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereais, milho, flocos, com sal', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereais, milho, flocos, sem sal', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereais, mingau, milho, infantil', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereais, mistura para vitamina, trigo, cevada e aveia', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereal matinal, milho', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereal matinal, milho, açúcar', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Creme de arroz, pó', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Creme de milho, pó', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Curau, milho verde', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Curau, milho verde, mistura para', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de arroz, enriquecida', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de centeio, integral', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de milho, amarela', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de rosca', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de trigo', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, láctea, de cereais', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lasanha, massa fresca, cozida', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lasanha, massa fresca, crua', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão, instantâneo', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão, trigo, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão, trigo, cru, com ovos', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho, amido, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho, fubá, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho, verde, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho, verde, enlatado, drenado', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'lt'],
            ['nome' => 'Mingau tradicional, pó', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pamonha, barra para cozimento, pré-cozida', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, aveia, forma', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, de soja', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, glúten, forma', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, milho, forma', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, trigo, forma, integral', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, trigo, francês', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, trigo, sovado', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, de carne, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, de carne, frito', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, de queijo, cru', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, de queijo, frito', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, massa, crua', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel, massa, frita', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pipoca, com óleo de soja, sem sal', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Polenta, pré-cozida', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Torrada, pão francês', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],

            // ─── VERDURAS E HORTALIÇAS ──────────────────────────────────
            ['nome' => 'Abóbora, cabotian, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora, cabotian, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora, menina brasileira, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora, moranga, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora, moranga, refogada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora, pescoço, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha, italiana, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha, italiana, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha, italiana, refogada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha, paulista, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Acelga, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Agrião, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Aipo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface, americana, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface, crespa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface, lisa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface, roxa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alfavaca, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alho, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alho-poró, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Almeirão, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Almeirão, refogado', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, baroa, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, baroa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, doce, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, doce, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, frita, tipo chips, industrializada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, inglesa, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, inglesa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, inglesa, frita', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata, inglesa, sauté', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Berinjela, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Berinjela, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Beterraba, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Beterraba, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito, polvilho doce', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Brócolis, cozido', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Brócolis, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cará, cozido', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cará, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Caruru, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Catalonha, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Catalonha, refogada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cebola, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cebolinha, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cenoura, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cenoura, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Chicória, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Chuchu, cozido', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Chuchu, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Coentro, folhas desidratadas', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve, manteiga, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve, manteiga, refogada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve-flor, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve-flor, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Espinafre, Nova Zelândia, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Espinafre, Nova Zelândia, refogado', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de mandioca, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de mandioca, torrada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de puba', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Fécula, de mandioca', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, broto, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Inhame, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Jiló, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Jurubeba, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mandioca, cozida', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mandioca, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mandioca, farofa, temperada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mandioca, frita', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Manjericão, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Maxixe, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mostarda, folha, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Nhoque, batata, cozido', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Nabo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Palmito, juçara, em conserva', 'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Palmito, pupunha, em conserva', 'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Pão, de queijo, assado', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão, de queijo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pepino, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão, amarelo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão, verde, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão, vermelho, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Polvilho, doce', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Quiabo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Rabanete, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Repolho, branco, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Repolho, roxo, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Repolho, roxo, refogado', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Rúcula, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Salsa, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Seleta de legumes, enlatada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Serralha, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Taioba, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate, com semente, cru', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate, extrato', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate, molho industrializado', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate, purê', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate, salada', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Vagem, crua', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],

            // ─── FRUTAS E DERIVADOS ─────────────────────────────────────
            ['nome' => 'Abacate, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Abacaxi, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Abacaxi, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Abiu, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Açaí, polpa, com xarope de guaraná e glucose', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Açaí, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Acerola, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Acerola, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ameixa, calda, enlatada', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Ameixa, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ameixa, em calda, enlatada, drenada', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Atemóia, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, da terra, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, doce em barra', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, figo, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, maçã, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, nanica, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, ouro, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, pacova, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana, prata, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cacau, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cajá-Manga, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cajá, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Caju, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Caju, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Caju, suco concentrado, envasado', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Caqui, chocolate, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Carambola, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ciriguela, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cupuaçu, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cupuaçu, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Figo, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Figo, enlatado, em calda', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Fruta-pão, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba, branca, com casca, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba, doce em pasta', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba, doce, cascão', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba, vermelha, com casca, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Graviola, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Graviola, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jabuticaba, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jaca, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jambo, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jamelão, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Kiwi, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, baía, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, baía, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, da terra, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, da terra, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, lima, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, lima, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, pêra, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, pêra, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, valência, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja, valência, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão, cravo, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão, galego, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão, tahiti, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maçã, Argentina, com casca, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maçã, Fuji, com casca, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Macaúba, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão, doce em calda, drenado', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão, Formosa, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão, Papaia, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão verde, doce em calda, drenado', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga, Haden, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga, Palmer, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga, Tommy Atkins, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maracujá, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maracujá, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maracujá, suco concentrado, envasado', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Melancia, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Melão, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mexerica, Murcote, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mexerica, Rio, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Morango, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Nêspera, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pequi, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêra, Park, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêra, Williams, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêssego, Aurora, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêssego, enlatado, em calda', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Pinha, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pitanga, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pitanga, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Romã, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tamarindo, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tangerina, Poncã, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tangerina, Poncã, suco', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tucumã, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Umbu, cru', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Umbu, polpa, congelada', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Uva, Itália, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Uva, Rubi, crua', 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Uva, suco concentrado, envasado', 'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],

            // ─── GORDURAS E ÓLEOS ───────────────────────────────────────
            ['nome' => 'Azeite, de dendê', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Azeite, de oliva, extra virgem', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Manteiga, com sal', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Manteiga, sem sal', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina, com óleo hidrogenado, com sal (65% de lipídeos)', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina, com óleo hidrogenado, sem sal (80% de lipídeos)', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina, com óleo interesterificado, com sal (65%de lipídeos)', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina, com óleo interesterificado, sem sal (65% de lipídeos)', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Óleo, de babaçu', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Óleo, de canola', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Óleo, de girassol', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Óleo, de milho', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Óleo, de pequi', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],
            ['nome' => 'Óleo, de soja', 'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'L'],

            // ─── PESCADOS E FRUTOS DO MAR ───────────────────────────────
            ['nome' => 'Abadejo, filé, congelado, assado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Abadejo, filé, congelado,cozido', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Abadejo, filé, congelado, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Abadejo, filé, congelado, grelhado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Atum, conserva em óleo', 'tipo_item' => 'pescado', 'unidade_medida' => 'lt'],
            ['nome' => 'Atum, fresco, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bacalhau, salgado, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bacalhau, salgado, refogado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cação, posta, com farinha de trigo, frita', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cação, posta, cozida', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cação, posta, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão, Rio Grande, grande, cozido', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão, Rio Grande, grande, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão, Sete Barbas, sem cabeça, com casca, frito', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Caranguejo, cozido', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corimba, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corimbatá, assado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corimbatá, cozido', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corvina de água doce, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corvina do mar, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corvina grande, assada', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corvina grande, cozida', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Dourada de água doce, fresca', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lambari, congelado, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lambari, congelado, frito', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lambari, fresco, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Manjuba, com farinha de trigo, frita', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Manjuba, frita', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Merluza, filé, assado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Merluza, filé, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Merluza, filé, frito', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, branca, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, branca, frita', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, filé, com farinha de trigo, frito', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, filé, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, filé, frito', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada, filé, molho escabeche', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescadinha, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pintado, assado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pintado, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pintado, grelhado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Porquinho, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salmão, filé, com pele, fresco,  grelhado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salmão, sem pele, fresco, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salmão, sem pele, fresco, grelhado', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sardinha, assada', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sardinha, conserva em óleo', 'tipo_item' => 'pescado', 'unidade_medida' => 'lt'],
            ['nome' => 'Sardinha, frita', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sardinha, inteira, crua', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tucunaré, filé, congelado, cru', 'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Apresuntado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Caldo de carne, tablete', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Caldo de galinha, tablete', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Carne, bovina, acém, moído, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, acém, moído, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, acém, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, acém, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, almôndegas, cruas', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, almôndegas, fritas', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, bucho, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, bucho, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, capa de contra-filé, com gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, capa de contra-filé, com gordura, grelhada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, capa de contra-filé, sem gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, capa de contra-filé, sem gordura, grelhada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, charque, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, charque, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé, à milanesa', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé de costela, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé de costela, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé, com gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé, com gordura, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, contra-filé, sem gordura, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, costela, assada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, costela, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, coxão duro, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, coxão duro, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, coxão mole, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, coxão mole, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, cupim, assado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, cupim, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, fígado, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, fígado, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, filé mingnon, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, filé mingnon, sem gordura, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, flanco, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, flanco, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, fraldinha, com gordura, cozida', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, fraldinha, com gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, lagarto, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, lagarto, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, língua, cozida', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, língua, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, maminha, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, maminha, grelhada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, miolo de alcatra, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, miolo de alcatra, sem gordura, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, músculo, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, músculo, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, paleta, com gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, paleta, sem gordura, cozida', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, paleta, sem gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, patinho, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, patinho, sem gordura, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, peito, sem gordura, cozido', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, peito, sem gordura, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, picanha, com gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, picanha, com gordura, grelhada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, picanha, sem gordura, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, picanha, sem gordura, grelhada', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, seca, cozida', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne, bovina, seca, crua', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Coxinha de frango, frita', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Croquete, de carne, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Croquete, de carne, frito', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Empada de frango, pré-cozida, assada', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Empada, de frango, pré-cozida', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, asa, com pele, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, caipira, inteiro, com pele, cozido', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, caipira, inteiro, sem pele, cozido', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coração, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coração, grelhado', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coxa, com pele, assada', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coxa, com pele, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coxa, sem pele, cozida', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, coxa, sem pele, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, fígado, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, filé, à milanesa', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, inteiro, com pele, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, inteiro, sem pele, assado', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, inteiro, sem pele, cozido', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Frango, inteiro, sem pele, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, peito, com pele, assado', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, peito, com pele, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, peito, sem pele, cozido', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, peito, sem pele, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, peito, sem pele, grelhado', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, sobrecoxa, com pele, assada', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, sobrecoxa, com pele, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, sobrecoxa, sem pele, assada', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, sobrecoxa, sem pele, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Hambúrguer, bovino, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Hambúrguer, bovino, frito', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Hambúrguer, bovino, grelhado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Lingüiça, frango, crua', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Lingüiça, frango, frita', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Lingüiça, frango, grelhada', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES SUÍNAS ──────────────────────────────────────────
            ['nome' => 'Lingüiça, porco, crua', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Lingüiça, porco, frita', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Lingüiça, porco, grelhada', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Mortadela', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],

            // ─── AVES ───────────────────────────────────────────────────
            ['nome' => 'Peru, congelado, assado', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Peru, congelado, cru', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES SUÍNAS ──────────────────────────────────────────
            ['nome' => 'Porco, bisteca, crua', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, bisteca, frita', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, bisteca, grelhada', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, costela, assada', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, costela, crua', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, lombo, assado', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, lombo, cru', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, orelha, salgada, crua', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, pernil, assado', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Porco, pernil, cru', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── CARNES SUÍNAS ──────────────────────────────────────────
            ['nome' => 'Porco, rabo, salgado, cru', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Presunto, com capa de gordura', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Presunto, sem capa de gordura', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ─────────────────────────────────────────
            ['nome' => 'Quibe, assado', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Quibe, cru', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Quibe, frito', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Salame', 'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── CARNES SUÍNAS ──────────────────────────────────────────
            ['nome' => 'Toucinho, cru', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Toucinho, frito', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],

            // ─── LEITE E DERIVADOS ──────────────────────────────────────
            ['nome' => 'Bebida láctea, pêssego', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Creme de Leite', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte, natural', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte, natural, desnatado', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte, sabor abacaxi', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte, sabor morango', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte, sabor pêssego', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite, condensado', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Leite, de cabra', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Leite, de vaca, achocolatado', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Leite, de vaca, desnatado, pó', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite, de vaca, desnatado, UHT', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Leite, de vaca, integral', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Leite, de vaca, integral, pó', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite, fermentado', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Queijo, minas, frescal', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, minas, meia cura', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, mozarela', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, parmesão', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, pasteurizado', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'laticinios', 'unidade_medida' => 'L'],
            ['nome' => 'Queijo, petit suisse, morango', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, prato', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, requeijão, cremoso', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo, ricota', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],

            // ─── BEBIDAS ────────────────────────────────────────────────
            ['nome' => 'Bebida isotônica, sabores variados', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Café, infusão 10%', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Cana, aguardente 1', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Cana, caldo de', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Cerveja, pilsen 2', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Chá, erva-doce, infusão 5%', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Chá, mate, infusão 5%', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Chá, preto, infusão 5%', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Coco, água de', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Refrigerante, tipo água tônica', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Refrigerante, tipo cola', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Refrigerante, tipo guaraná', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Refrigerante, tipo laranja', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],
            ['nome' => 'Refrigerante, tipo limão', 'tipo_item' => 'bebida', 'unidade_medida' => 'L'],

            // ─── OVOS ───────────────────────────────────────────────────
            ['nome' => 'Omelete, de queijo', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de codorna, inteiro, cru', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de galinha, clara, cozida/10minutos', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de galinha, gema, cozida/10minutos', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de galinha, inteiro, cozido/10minutos', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de galinha, inteiro, cru', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo, de galinha, inteiro, frito', 'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],

            // ─── PRODUTOS AÇUCARADOS ────────────────────────────────────
            ['nome' => 'Achocolatado, pó', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar, cristal', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar, mascavo', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar, refinado', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate, ao leite', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate, ao leite, com castanha do Pará', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate, ao leite, dietético', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate, meio amargo', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Cocada branca', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce, de abóbora, cremoso', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce, de leite, cremoso', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Geléia, mocotó, natural', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Glicose de milho', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Maria mole', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Maria mole, coco queimado', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Marmelada', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Mel, de abelha', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Melado', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Quindim', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Rapadura', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],

            // ─── MISCELÂNEAS/CONDIMENTOS ────────────────────────────────
            ['nome' => 'Café, pó, torrado', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Capuccino, pó', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Fermento em pó, químico', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Fermento, biológico, levedura, tablete', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Gelatina, sabores variados, pó', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Sal, dietético', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Sal, grosso', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Shoyu', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Tempero a base de sal', 'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],

            // ─── INDUSTRIALIZADOS/PREPARADOS ────────────────────────────
            ['nome' => 'Azeitona, preta, conserva', 'tipo_item' => 'industrializado', 'unidade_medida' => 'lt'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Azeitona, verde, conserva', 'tipo_item' => 'industrializado', 'unidade_medida' => 'lt'],
            ['nome' => 'Chantilly, spray, com gordura vegetal', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite, de coco', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Maionese, tradicional com ovos', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Acarajé', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz carreteiro', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Baião de dois, arroz e feijão-de-corda', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Barreado', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bife à cavalo, com contra filé', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolinho de arroz', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão à baiana', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Charuto, de repolho', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cuscuz, de milho, cozido com sal', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cuscuz, paulista', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cuxá, molho', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Dobradinha', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Estrogonofe de carne', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Estrogonofe de frango', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão tropeiro mineiro', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'L', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango, com açafrão', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão, molho bolognesa', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Maniçoba', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Quibebe', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salada, de legumes, com maionese', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salada, de legumes, cozida no vapor', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salpicão, de frango', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sarapatel', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tabule', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tacacá', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tapioca, com manteiga', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tucupi, com pimenta-de-cheiro', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Vaca atolada', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Vatapá', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Virado à paulista', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Yakisoba', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],

            // ─── LEGUMINOSAS ────────────────────────────────────────────
            ['nome' => 'Amendoim, grão, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Amendoim, torrado, salgado', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Ervilha, em vagem', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Ervilha, enlatada, drenada', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'lt'],
            ['nome' => 'Feijão, carioca, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, carioca, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, fradinho, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, fradinho, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, jalo, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, jalo, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, preto, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, preto, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, rajado, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, rajado, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, rosinha, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, rosinha, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, roxo, cozido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão, roxo, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Grão-de-bico, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Guandu, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Lentilha, cozida', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Descrição dos alimentos', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Lentilha, crua', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Paçoca, amendoim', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pé-de-moleque, amendoim', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Soja, farinha', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Soja, extrato solúvel, natural, fluido', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Soja, extrato solúvel, pó', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Soja, queijo (tofu)', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Tremoço, cru', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Tremoço, em conserva', 'tipo_item' => 'leguminosa', 'unidade_medida' => 'lt'],

            // ─── NOZES E SEMENTES ───────────────────────────────────────
            ['nome' => 'Amêndoa, torrada, salgada', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Castanha-de-caju, torrada, salgada', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Castanha-do-Brasil, crua', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Coco, cru', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Coco,  verde, cru', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha, de mesocarpo de babaçu, crua', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Gergelim, semente', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Linhaça, semente', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pinhão, cozido', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pupunha, cozida', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Noz, crua', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'as análises estão sendo reavaliadas', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Valores em branco nesta tabela: análises não solicitadas', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Teores alcoólicos (g/100g): ¹ Cana, aguardente: 31,1 e ² Cerveja, pilsen: 3,6.', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Abreviações: g: grama; mg: micrograma; kcal: kilocaloria; kJ: kilojoule; mg:miligrama; NA: não aplicável; Tr: traço. Adotou-se traço nas seguintes situações: a)valores de nutrientes arredondados para números que caiam entre 0 e 0,5; b) valores de nutrientes arredondados para números com uma casa decimal que caiam entre 0 e 0,05; c) valores de nutrientes arredondados para números com duas casas decimais que caiam entre 0 e 0,005 e; d) valores abaixo dos limites de quantificação (29).', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Limites de Quantificação: a) composição centesimal: 0,1g/100g; b) colesterol: 1mg/100g; c) Cu, Fe, Mn, e Zn: 0,001mg/100g; d) Ca, Na: 0,04mg/100g; e) K e P: 0,001mg/100g; f) Mg 0,015mg/100g; g) tiamina, riboflavina e piridoxina: 0,03mg/100g; h) niacina e vitamina C: 1mg/100g; i) retinol em produtos cárneos e outros: 3μg/100g e; j) retinol em lácteos: 20μg/100g.', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Valores correspondentes à somatória do resultado analítico do retinol mais o valor calculado com base no teor de carotenóides segundo o livro Fontes brasileiras de carotenóides: tabela brasileira de composição de carotenóides em alimentos.', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Valores retirados do livro Fontes brasileiras de carotenóides: tabela brasileira de composição de carotenóides em alimentos.', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
        ];

        foreach ($itens as $item) {
            Item::firstOrCreate(
                ['nome' => $item['nome']],
                [
                    'tipo_item'      => $item['tipo_item'],
                    'unidade_medida' => $item['unidade_medida'],
                    'ativo'          => true,
                ]
            );
        }
    }
}