<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItensSeeder extends Seeder
{
    public function run(): void
    {
        $itens = [
            // ─── CEREAIS E DERIVADOS ─────────────────────────────────────
            ['nome' => 'Arroz integral',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz tipo 1',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz tipo 2',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Aveia em flocos',             'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito maisena',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito recheado chocolate', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito recheado morango',   'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito wafer chocolate',    'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito wafer morango',      'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito cream cracker',      'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Mistura para bolo',           'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo de aipim',               'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo de chocolate',           'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo de coco',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolo de milho',               'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Canjica branca',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Flocos de milho com sal',     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Flocos de milho sem sal',     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Mingau infantil de milho',    'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Mistura para vitamina',       'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cereal matinal de milho',     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Creme de arroz',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Creme de milho',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de arroz',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de centeio integral', 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de milho',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de rosca',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de trigo',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha láctea',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lasanha fresca',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão instantâneo',        'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão de trigo',           'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão com ovos',           'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Amido de milho',              'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Fubá',                        'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho verde',                 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Milho verde enlatado',        'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'lt'],
            ['nome' => 'Mingau tradicional',          'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pamonha',                     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão de aveia',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão de soja',                 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão de glúten',               'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão de milho',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão integral',                'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão francês',                 'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pão sovado',                  'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel de carne',             'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pastel de queijo',            'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Massa de pastel',             'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pipoca',                      'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Polenta',                     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],
            ['nome' => 'Torrada',                     'tipo_item' => 'cereal_derivado', 'unidade_medida' => 'kg'],

            // ─── VERDURAS E HORTALIÇAS ────────────────────────────────────
            ['nome' => 'Abóbora cabotiã',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora menina',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora moranga',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abóbora pescoço',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha italiana', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Abobrinha paulista', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Acelga',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Agrião',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Aipo',               'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface americana',   'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface crespa',      'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface lisa',        'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alface roxa',        'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alfavaca',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alho',               'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Alho-poró',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Almeirão',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata baroa',       'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata doce',        'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata chips',       'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Batata inglesa',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Berinjela',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Beterraba',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Biscoito de polvilho','tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Brócolis',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cará',               'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Caruru',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Catalonha',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cebola',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cebolinha',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Cenoura',            'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Chicória',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Chuchu',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Coentro desidratado','tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve manteiga',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Couve-flor',         'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Espinafre',          'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de mandioca','tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de puba',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Fécula de mandioca', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Broto de feijão',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Inhame',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Jiló',               'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Jurubeba',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mandioca',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Farofa de mandioca', 'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Manjericão',         'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Maxixe',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Mostarda',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Nhoque de batata',   'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Nabo',               'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Palmito juçara',     'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Palmito pupunha',    'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Pão de queijo',      'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pepino',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão amarelo',   'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão verde',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Pimentão vermelho',  'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Polvilho doce',      'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Quiabo',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Rabanete',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Repolho branco',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Repolho roxo',       'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Rúcula',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Salsa',              'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Seleta de legumes',  'tipo_item' => 'hortalica', 'unidade_medida' => 'lt'],
            ['nome' => 'Serralha',           'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Taioba',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Tomate',             'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Extrato de tomate',  'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Molho de tomate',    'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Purê de tomate',     'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],
            ['nome' => 'Vagem',              'tipo_item' => 'hortalica', 'unidade_medida' => 'kg'],

            // ─── FRUTAS E DERIVADOS ───────────────────────────────────────
            ['nome' => 'Abacate',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Abacaxi',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de abacaxi',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Abiu',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Açaí',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de açaí',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Acerola',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de acerola',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ameixa',               'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ameixa em calda',      'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Atemóia',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana da terra',      'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana figo',          'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana maçã',          'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana nanica',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana ouro',          'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Banana prata',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce de banana',       'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cacau',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cajá-manga',           'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de cajá',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Caju',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de caju',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Suco de caju',         'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Caqui',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Carambola',            'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Ciriguela',            'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Cupuaçu',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de cupuaçu',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Figo',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Figo em calda',        'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Fruta-pão',            'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba branca',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Goiaba vermelha',      'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce de goiaba',       'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Graviola',             'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de graviola',    'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jabuticaba',           'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jaca',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jambo',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Jamelão',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Kiwi',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja baía',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja da terra',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja lima',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja pêra',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Laranja valência',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão cravo',          'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão galego',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Limão tahiti',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maçã argentina',       'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maçã fuji',            'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Macaúba',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão formosa',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mamão papaia',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce de mamão',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga haden',          'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga palmer',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Manga tommy atkins',   'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de manga',       'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Maracujá',             'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de maracujá',    'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Suco de maracujá',     'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Melancia',             'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Melão',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mexerica murcote',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Mexerica rio',         'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Morango',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Nêspera',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pequi',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêra',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêssego',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pêssego em calda',     'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],
            ['nome' => 'Pinha',                'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Pitanga',              'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de pitanga',     'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Romã',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tamarindo',            'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tangerina poncã',      'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Tucumã',               'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Umbu',                 'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Polpa de umbu',        'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Uva itália',           'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Uva rubi',             'tipo_item' => 'fruta', 'unidade_medida' => 'kg'],
            ['nome' => 'Suco de uva',          'tipo_item' => 'fruta', 'unidade_medida' => 'lt'],

            // ─── GORDURAS E ÓLEOS ─────────────────────────────────────────
            ['nome' => 'Azeite de dendê',        'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Azeite de oliva',        'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Manteiga com sal',        'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Manteiga sem sal',        'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina com sal',       'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Margarina sem sal',       'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'kg'],
            ['nome' => 'Óleo de babaçu',          'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Óleo de canola',          'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Óleo de girassol',        'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Óleo de milho',           'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Óleo de pequi',           'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],
            ['nome' => 'Óleo de soja',            'tipo_item' => 'oleo_gordura', 'unidade_medida' => 'lt'],

            // ─── PESCADOS ─────────────────────────────────────────────────
            ['nome' => 'Abadejo',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Atum em óleo', 'tipo_item' => 'pescado', 'unidade_medida' => 'lt'],
            ['nome' => 'Atum fresco',  'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bacalhau',     'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cação',        'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Caranguejo',   'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corimba',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corimbatá',    'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Corvina',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Dourada',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Lambari',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Manjuba',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Merluza',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pescada',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Pintado',      'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salmão',       'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sardinha',     'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sardinha em óleo', 'tipo_item' => 'pescado', 'unidade_medida' => 'lt'],
            ['nome' => 'Tucunaré',     'tipo_item' => 'pescado', 'unidade_medida' => 'kg'],

            // ─── CARNES BOVINAS ───────────────────────────────────────────
            ['nome' => 'Apresuntado',     'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Caldo de carne',  'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Acém bovino',     'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Almôndega',       'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Bucho bovino',    'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Contra-filé',     'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Charque',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Costela bovina',  'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Coxão duro',      'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Coxão mole',      'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Cupim',           'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Fígado bovino',   'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Filé mignon',     'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Flanco bovino',   'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Fraldinha',       'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Lagarto',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Língua bovina',   'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Maminha',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Alcatra',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Músculo bovino',  'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Paleta bovina',   'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Patinho',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Peito bovino',    'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Picanha',         'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Carne seca',      'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Croquete de carne','tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Hambúrguer',      'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Quibe',           'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],
            ['nome' => 'Salame',          'tipo_item' => 'carne_bovina', 'unidade_medida' => 'kg'],

            // ─── AVES ─────────────────────────────────────────────────────
            ['nome' => 'Caldo de galinha',  'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Coxinha de frango', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Empada de frango',  'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Asa de frango',     'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango caipira',    'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Coração de frango', 'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Coxa de frango',    'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Fígado de frango',  'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Filé de frango',    'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango inteiro',    'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Peito de frango',   'tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Sobrecoxa de frango','tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Linguiça de frango','tipo_item' => 'ave', 'unidade_medida' => 'kg'],
            ['nome' => 'Peru',              'tipo_item' => 'ave', 'unidade_medida' => 'kg'],

            // ─── CARNES SUÍNAS ────────────────────────────────────────────
            ['nome' => 'Linguiça de porco', 'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Mortadela',         'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Bisteca suína',     'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Costela suína',     'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Lombo suíno',       'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Orelha suína',      'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Pernil suíno',      'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Rabo suíno',        'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Presunto',          'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],
            ['nome' => 'Toucinho',          'tipo_item' => 'carne_suina', 'unidade_medida' => 'kg'],

            // ─── LEITE E DERIVADOS ────────────────────────────────────────
            ['nome' => 'Bebida láctea',          'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Creme de leite',         'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte natural',        'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte desnatado',      'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte abacaxi',        'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte morango',        'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Iogurte pêssego',        'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite condensado',       'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Leite de cabra',         'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Leite achocolatado',     'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Leite desnatado em pó',  'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite desnatado UHT',    'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Leite integral',         'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Leite integral em pó',   'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite fermentado',       'tipo_item' => 'laticinios', 'unidade_medida' => 'lt'],
            ['nome' => 'Queijo minas frescal',   'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo minas meia cura', 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo mozzarella',      'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo parmesão',        'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo pasteurizado',    'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo petit suisse',    'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Queijo prato',           'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Requeijão cremoso',      'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],
            ['nome' => 'Ricota',                 'tipo_item' => 'laticinios', 'unidade_medida' => 'kg'],

            // ─── BEBIDAS ──────────────────────────────────────────────────
            ['nome' => 'Bebida isotônica',  'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Café',              'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Aguardente',        'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Caldo de cana',     'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Cerveja',           'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Chá de erva-doce',  'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Chá mate',          'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Chá preto',         'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Água de coco',      'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Refrigerante tônica','tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Refrigerante cola', 'tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Refrigerante guaraná','tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Refrigerante laranja','tipo_item' => 'bebida', 'unidade_medida' => 'lt'],
            ['nome' => 'Refrigerante limão','tipo_item' => 'bebida', 'unidade_medida' => 'lt'],

            // ─── OVOS ─────────────────────────────────────────────────────
            ['nome' => 'Omelete de queijo',  'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo de codorna',     'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],
            ['nome' => 'Ovo de galinha',     'tipo_item' => 'ovo', 'unidade_medida' => 'dz'],

            // ─── PRODUTOS AÇUCARADOS ──────────────────────────────────────
            ['nome' => 'Achocolatado em pó',    'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar cristal',        'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar mascavo',        'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Açúcar refinado',       'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate ao leite',    'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Chocolate meio amargo', 'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Cocada',                'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce de abóbora',       'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Doce de leite',         'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Geléia de mocotó',      'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Glicose de milho',      'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Maria mole',            'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Marmelada',             'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Mel de abelha',         'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Melado',                'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Quindim',               'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],
            ['nome' => 'Rapadura',              'tipo_item' => 'acucar_doce', 'unidade_medida' => 'kg'],

            // ─── CONDIMENTOS ──────────────────────────────────────────────
            ['nome' => 'Café em pó',        'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Cappuccino',        'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Fermento em pó',    'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Fermento biológico','tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Gelatina',          'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Sal dietético',     'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Sal grosso',        'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Shoyu',             'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],
            ['nome' => 'Tempero com sal',   'tipo_item' => 'condimento', 'unidade_medida' => 'kg'],

            // ─── INDUSTRIALIZADOS/PREPARADOS ──────────────────────────────
            ['nome' => 'Azeitona preta',        'tipo_item' => 'industrializado', 'unidade_medida' => 'lt'],
            ['nome' => 'Azeitona verde',        'tipo_item' => 'industrializado', 'unidade_medida' => 'lt'],
            ['nome' => 'Chantilly',             'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Leite de coco',         'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Maionese',              'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Acarajé',               'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Arroz carreteiro',      'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Baião de dois',         'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Barreado',              'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bife à cavalo',         'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Bolinho de arroz',      'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Camarão à baiana',      'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Charuto de repolho',    'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cuscuz de milho',       'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Cuscuz paulista',       'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Molho cuxá',            'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Dobradinha',            'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Estrogonofe de carne',  'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Estrogonofe de frango', 'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão tropeiro',       'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Frango com açafrão',    'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Macarrão bolognesa',    'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Maniçoba',              'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Quibebe',               'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salada de legumes',     'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Salpicão de frango',    'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Sarapatel',             'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tabule',                'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tacacá',                'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tapioca',               'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Tucupi',                'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Vaca atolada',          'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Vatapá',                'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Virado à paulista',     'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],
            ['nome' => 'Yakisoba',              'tipo_item' => 'industrializado', 'unidade_medida' => 'kg'],

            // ─── LEGUMINOSAS ──────────────────────────────────────────────
            ['nome' => 'Amendoim',          'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Ervilha',           'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Ervilha enlatada',  'tipo_item' => 'leguminosa', 'unidade_medida' => 'lt'],
            ['nome' => 'Feijão carioca',    'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão fradinho',   'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão jalo',       'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão preto',      'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão rajado',     'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão rosinha',    'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Feijão roxo',       'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Grão-de-bico',      'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Guandu',            'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Lentilha',          'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Paçoca',            'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pé-de-moleque',     'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de soja',   'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Extrato de soja',   'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Tofu',              'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Tremoço',           'tipo_item' => 'leguminosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Tremoço em conserva','tipo_item' => 'leguminosa', 'unidade_medida' => 'lt'],

            // ─── NOZES E SEMENTES ─────────────────────────────────────────
            ['nome' => 'Amêndoa',            'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Castanha de caju',   'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Castanha do Brasil', 'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Coco',               'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Farinha de babaçu',  'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Gergelim',           'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Linhaça',            'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pinhão',             'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Pupunha',            'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
            ['nome' => 'Noz',                'tipo_item' => 'semente_oleaginosa', 'unidade_medida' => 'kg'],
        ];

        foreach ($itens as $item) {
            Item::firstOrCreate(
                ['nome' => $item['nome']],
                [
                    'tipo_item'      => $item['tipo_item'],
                    'unidade_medida' => $item['unidade_medida'],
                    'ativo'          => true,
                ]
            );
        }
    }
}