<?php

namespace App\Models\Enums;

enum ListaPermissoes: string
{
    case ListarAlunos = 'listar alunos';
    case ListarRelatoriosProfessorPorComponenteETurma = 'listar relatórios: professor por componente e turma';
    case ListarRelatoriosComponentesComProfessoresFaltando = 'listar relatórios: componentes com professores faltando';
    case ListarRelatoriosDashboard = 'listar relatórios: dashboard';
    case ListarTipoManutencao = 'listar tipo manutenção';
    case ListarTipoStatus = 'listar tipo status';
    case ListarPedidos = 'listar pedidos';
    case ListarTodosOsPedidos = 'listar todos os pedidos';
    case ListarEmpresaContratada = 'listar empresa contratada';
    case ListarEmpresasInativas = 'listar empresas inativas';
    case ListarUsuarios = 'listar usuários';
    case ListarNiveisDeAcesso = 'listar níveis de acesso';
    case ListarPermissoesDeExecucao = 'listar permissões de execução';
    case ListarDominiosDeEmail = 'listar dominios de email';
    case ListarEscolas = 'listar escolas';
    case ListarTurmas = 'listar turmas';
    case ListarSeries = 'listar séries';
    case ListarProfessores = 'listar professores';
    case ListarFuncoesAdministrativas = 'listar funções administrativas';
    case ListarAlternativas = 'listar alternativas';
    case ListarPautas = 'listar pautas';
    case ListarAvaliacoes = 'listar avaliações';
    case AcompanharAvaliacoes = 'acompanhar avaliações';
    case VisualizarProgressoPorEscola = 'visualizar progresso por escola';
    case ListarTiposDeAvaliacoes = 'listar tipos de avaliações';
    case ListarContratos = 'listar contratos';
    case ListarPedidosMerenda = 'listar pedidos: merenda';
    case ListarInventarios = 'listar inventários';
    case ListarGestaoDeInventario = 'listar gestão de inventário';
    case ListarPedidosDeInventario = 'listar pedidos de inventário';
    case ListarBalancosDeInventario = 'listar balanços de inventário';
    case ListarGestaoDeEstoque = 'listar gestão de estoque';
    case ListarBalancosDeEstoque = 'listar balanços de estoque';
    case ListarGestaoDeMargens = 'listar gestão de margens';
    case ListarItens = 'listar itens';
    case ListarComponenteCurricular = 'listar componente curricular';
    case ListarSetores = 'listar setores';
    case ListarServidores = 'listar servidores';
    case ListarPessoas = 'listar pessoas';
    case ListarAvisos = 'listar avisos';
    case ListarEventos = 'listar eventos';
    case ListarEventosTransporte = 'listar eventos: transporte';
    case ListarEventosGeral = 'listar eventos: geral';
    case ListarMeusEventos = 'listar eventos: meus eventos';
    case ListarReservasVeiculos = 'listar reservas de veículos';
    case ListarSaldoEleitoral = 'listar saldo eleitoral';

    case CriarEmpresaContratada = 'criar empresa contratada';
    case CriarAlunos = 'criar alunos';
    case ImportarAlunosPorPlanilha = 'importar alunos por planilha';
    case RealizarTransferenciaDeAluno = 'realizar transferencia de aluno';
    case RealizarRemanejamentoDeAluno = 'realizar remanejamento de aluno';
    case GerarParecerDeTransferencia = 'gerar parecer de transferencia';
    case NotificarStatusPendente = 'notificar status pendente';
    case NotificarImpedimentoDeMatriculaPorFaltaDeTransferencia = 'notificar impedimento de matricula por falta de transferencia';
    case GerenciarImpedimentoDeMatriculaPorFaltaDeTransferencia = 'gerenciar impedimento de matricula por falta de transferencia';
    case CriarTipoManutencao = 'criar tipo manutenção';
    case CriarTipoStatus = 'criar tipo status';
    case CriarPedidos = 'criar pedidos';
    case CriarUsuarios = 'criar usuários';
    case CriarNiveisDeAcesso = 'criar níveis de acesso';
    case CriarPermissoesDeExecucao = 'criar permissões de execução';
    case CriarDominiosDeEmail = 'criar dominios de email';
    case CriarSeries = 'criar séries';
    case CriarEscolas = 'criar escolas';
    case CriarTurmas = 'criar turmas';
    case CriarProfessores = 'criar professores';
    case CriarAlternativas = 'criar alternativas';
    case CriarPautas = 'criar pautas';
    case CriarAvaliacoes = 'criar avaliações';
    case CriarFuncoesAdministrativas = 'criar funções administrativas';
    case CriarTiposDeAvaliacoes = 'criar tipos de avaliações';
    case CriarContratos = 'criar contratos';
    case CriarPedidosMerenda = 'criar pedidos: merenda';
    case CriarInventarios = 'criar inventários';
    case CriarPedidosDeInventario = 'criar pedidos de inventário';
    case CriarBalancosDeInventario = 'criar balanços de inventário';
    case CriarBalancosDeEstoque = 'criar balanços de estoque';
    case CriarItens = 'criar itens';
    case CriarComponenteCurricular = 'criar componente curricular';
    case CriarSetores = 'criar setores';
    case CriarServidores = 'criar servidores';
    case CriarPessoas = 'criar pessoas';
    case CriarAvisos = 'criar avisos';
    case CriarEventos = 'criar eventos';
    case CriarEventosTransporte = 'criar eventos: transporte';
    case CriarReservasVeiculos = 'criar reservas de veículos';
    case SolicitarAdicaoSaldoEleitoral = 'solicitar adição de saldo eleitoral';
    case SolicitarUsoSaldoEleitoral = 'solicitar uso de saldo eleitoral';
    case GerenciarSaldoEleitoral = 'gerenciar saldo eleitoral';

    case EditarEmpresaContratada = 'editar empresa contratada';
    case EditarAlunos = 'editar alunos';
    case EditarPedidos = 'editar pedidos';
    case EditarCamposDaEscola = 'editar campos da escola';
    case EditarCodigoDaEscola = 'editar codigo da escola';
    case EditarEscolaDoAluno = 'editar escola do aluno';
    case EditarEscolaDaTurma = 'editar escola da turma';
    case EditarEscolaDoUsuario = 'editar escola do usuario';
    case EditarEscolaDoProfessor = 'editar escola do professor';
    case EditarMatriculaDoProfessor = 'editar matricula do professor';
    case EditarNomeDoProfessor = 'editar nome do professor';
    case EditarEspecializacoesDeProfessores = 'editar especializações de professores';
    case EditarDadosDaTurma = 'editar dados da turma';
    case EditarTurmas = 'editar turmas';
    case EditarTipoManutencao = 'editar tipo manutenção';
    case EditarTipoStatus = 'editar tipo status';
    case EditarSetorDoUsuario = 'editar setor do usuário';
    case EditarUsuarios = 'editar usuários';
    case RedefinirSenhasDeUsuarios = 'redefinir senhas de usuários';
    case EditarNiveisDeAcesso = 'editar níveis de acesso';
    case EditarPermissoesDeExecucao = 'editar permissões de execução';
    case EditarDominiosDeEmail = 'editar dominios de email';
    case EditarSeries = 'editar séries';
    case EditarEscolas = 'editar escolas';
    case GerenciarLotacoes = 'gerenciar lotações';
    case EditarProfessores = 'editar professores';
    case EditarFuncoesAdministrativas = 'editar funções administrativas';
    case EditarAlternativas = 'editar alternativas';
    case EditarPautas = 'editar pautas';
    case EditarAvaliacoes = 'editar avaliações';
    case EditarTiposDeAvaliacoes = 'editar tipos de avaliações';
    case EditarContratos = 'editar contratos';
    case EditarPedidosMerenda = 'editar pedidos: merenda';
    case EditarItens = 'editar itens';
    case EditarComponenteCurricular = 'editar componente curricular';
    case EditarDadosDoProfessor = 'editar dados do professor';
    case EditarSetores = 'editar setores';
    case EditarServidores = 'editar servidores';
    case EditarPessoas = 'editar pessoas';
    case EditarDadosDePessoas = 'editar dados de pessoas';
    case EditarTurmasEComponentesDePessoas = 'editar turmas e componentes de pessoas';
    case EditarAvisos = 'editar avisos';
    case EditarEventos = 'editar eventos';
    case EditarReservasVeiculos = 'editar reservas de veículos';

    case GerenciarFuncoesDeServidores = 'gerenciar funções de servidores';
    case GerenciarVinculosEstruturaisDePessoas = 'gerenciar vínculos estruturais de pessoas';
    case GerenciarPublicoAlvoDeAvisos = 'gerenciar público-alvo de avisos';
    case GerenciarPublicoAlvoDeEventos = 'gerenciar público-alvo de eventos';
    case GerenciarTransporteDeEventos = 'gerenciar transporte de eventos';
    case GerenciarFrotaVeiculos = 'gerenciar frota de veículos';
    case CancelarReservasVeiculos = 'cancelar reservas de veículos';
    case TransferirProfessores = 'transferir professores';
    case DesativarProfessores = 'desativar professores';
    case DesativarEventos = 'desativar eventos';
    case DesativarEventosTransporte = 'desativar eventos: transporte';
    case RejeitarEventosTransporte = 'rejeitar eventos: transporte';

    case ExcluirEmpresaContratada = 'excluir empresa contratada';
    case ExcluirAlunos = 'excluir alunos';
    case ExcluirTipoManutencao = 'excluir tipo manutenção';
    case ExcluirTipoStatus = 'excluir tipo status';
    case ExcluirPedidos = 'excluir pedidos';
    case ExcluirUsuarios = 'excluir usuários';
    case ExcluirNiveisDeAcesso = 'excluir níveis de acesso';
    case ExcluirPermissoesDeExecucao = 'excluir permissões de execução';
    case ExcluirDominiosDeEmail = 'excluir dominios de email';
    case ExcluirSeries = 'excluir séries';
    case ExcluirEscolas = 'excluir escolas';
    case ExcluirTurmas = 'excluir turmas';
    case ExcluirProfessores = 'excluir professores';
    case ExcluirAlternativas = 'excluir alternativas';
    case ExcluirPautas = 'excluir pautas';
    case ExcluirAvaliacoes = 'excluir avaliações';
    case ExcluirFuncoesAdministrativas = 'excluir funções administrativas';
    case ExcluirTiposDeAvaliacoes = 'excluir tipos de avaliações';
    case ExcluirContratos = 'excluir contratos';
    case ExcluirSetores = 'excluir setores';
    case ExcluirServidores = 'excluir servidores';
    case ExcluirPessoas = 'excluir pessoas';
    case ExcluirPessoasDefinitivamente = 'excluir pessoas definitivamente';
    case ExcluirComponenteCurricular = 'excluir componente curricular';
    case ExcluirPedidosMerenda = 'excluir pedidos: merenda';
    case ExcluirItens = 'excluir itens';
    case ExcluirEmpresaContratadaEmMassa = 'excluir empresa contratada em massa';
    case ExcluirAlunosEmMassa = 'excluir alunos em massa';
    case ExcluirTurmasEmMassa = 'excluir turmas em massa';
    case ExcluirProfessoresEmMassa = 'excluir professores em massa';
    case ExcluirTiposDeManutencaoEmMassa = 'excluir tipos de manutenção em massa';
    case ExcluirTipoStatusEmMassa = 'excluir tipo status em massa';
    case ExcluirPedidosEmMassa = 'excluir pedidos em massa';
    case ExcluirAlternativasEmMassa = 'excluir alternativas em massa';
    case ExcluirFuncoesAdministrativasEmMassa = 'excluir funções administrativas em massa';
    case ExcluirTiposDeAvaliacoesEmMassa = 'excluir tipos de avaliações em massa';
    case ExcluirSetoresEmMassa = 'excluir setores em massa';
    case ExcluirItensEmMassa = 'excluir itens em massa';
    case ExcluirAvisos = 'excluir avisos';
    case ExcluirEventos = 'excluir eventos';

    case ExportarAlunos = 'exportar alunos';
    case ExportarModeloDeImportacaoDeAlunos = 'exportar modelo de importacao de alunos';
    case ExportarTurmas = 'exportar turmas';
    case ExportarEscolas = 'exportar escolas';
    case ExportarRelatorios = 'exportar relatórios';
    case ExportarAvaliacoes = 'exportar avaliações';
    case ExportarProfessores = 'exportar professores';
    case ExportarArquivosPedido = 'exportar arquivos pedido';
    case ExportarComponenteCurricular = 'exportar componente curricular';
    case ExportarModeloDeImportacaoDeEventos = 'exportar modelo de importação de eventos';
    case ImportarEventosPorPlanilha = 'importar eventos por planilha';

    case VisualizarDetalhesDeAluno = 'visualizar detalhes de aluno';
    case VisualizarProfessores = 'visualizar professores';
    case VisualizarUsuariosOnline = 'visualizar usuarios online';
    case VisualizarSelectDePerfis = 'visualizar select de perfis';
    case VisualizarNotificacoes = 'visualizar notificações';
    case CriarNotificacoes = 'criar notificações';
    case EnviarNotificacoesTodosOsUsuarios = 'enviar notificações: todos os usuários';
    case EnviarNotificacoesUsuariosEspecificos = 'enviar notificações: usuários específicos';
    case EnviarNotificacoesNiveisDeAcesso = 'enviar notificações: níveis de acesso';
    case EnviarNotificacoesUsuariosPorEscola = 'enviar notificações: usuários por escola';
    case EnviarNotificacoesProfessoresPorTurma = 'enviar notificações: professores por turma';
    case EnviarNotificacoesUsuariosPorPermissao = 'enviar notificações: usuários por permissão';
    case EnviarNotificacoesSetorEspecifico = 'enviar notificações: setor específico';
    case VisualizarEspecializacoesDeProfessores = 'visualizar especializações de professores';
    case VisualizarDetalhesDeProfessor = 'visualizar detalhes de professor';
    case VisualizarSetorDoUsuario = 'visualizar setor do usuário';
    case VisualizarStatusEncaminhadoAoSetor = 'visualizar status: encaminhado ao setor';
    case VisualizarHistoricoDePedidos = 'visualizar histórico de pedidos';
    case VisualizarArquivosDePedidos = 'visualizar arquivos de pedidos';
    case VisualizarPedidosPorStatus = 'visualizar pedidos por status';
    case VisualizarPainelPersonalizado = 'visualizar painel personalizado';
    case VisualizarFeedbackDePedidos = 'visualizar feedback de pedidos';
    case VisualizarNotificacaoVencimentoDePedidos = 'visualizar notificação: vencimento de pedidos';
    case VisualizarNotificacaoPedidosAtrasados = 'visualizar notificação: pedidos atrasados';
    case VisualizarNotificacaoPedidosEmergenciais = 'visualizar notificação: pedidos emergenciais';
    case VisualizarNotificacaoPedidoReaberto = 'visualizar notificação: pedido reaberto';
    case VisualizarNotificacaoPedidoAdicionalCriado = 'visualizar notificação: pedido adicional criado';
    case VisualizarNotificacaoBalancoDeEstoque = 'visualizar notificação: balanço de estoque';
    case VisualizarTelaDeInicio = 'visualizar tela de inicio';
    case VisualizarAgendaDeTodaARede = 'visualizar agenda de toda a rede';
    case PublicarAvisos = 'publicar avisos';
    case PublicarEventos = 'publicar eventos';
    case PublicarEventosTransporte = 'publicar eventos: transporte';

    case AcessarEscopoGlobalDeSetores = 'acessar escopo global de setores';
    case BaixarApp = 'baixar app';

    case FiltrarAlunosPorEscola = 'filtrar alunos por escola';
    case FiltrarProfessoresPorEscola = 'filtrar professores por escola';
    case FiltrarProfessoresPorComponente = 'filtrar professores por componente';
    case FiltrarProfessoresPorSerie = 'filtrar professores por serie';
    case FiltrarTurmasPorEscola = 'filtrar turmas por escola';

    case AplicarPermissoes = 'aplicar permissoes';
    case AvaliarPedidos = 'avaliar pedidos';
    case ComentarPedidos = 'comentar pedidos';
    case EncaminharPedidosParaSetor = 'encaminhar pedidos para setor';
    case EnviarPedidosParaEmpresa = 'enviar pedidos para empresa';
    case VincularPedidosAdicionais = 'vincular pedidos adicionais';
    case ResponderAvaliacoes = 'responder avaliações';
    case PreencherAvaliacoesEmMassa = 'preencher avaliações em massa';
    case ConcluirAvaliacoes = 'concluir avaliações';
    case ReabrirAvaliacoes = 'reabrir avaliações';
    case AprovarPedidosDeInventario = 'aprovar pedidos de inventário';
    case GerarRomaneiosDeInventario = 'gerar romaneios de inventário';
    case ConferirPedidosDeInventario = 'conferir pedidos de inventário';
    case IniciarBalancosDeInventario = 'iniciar balanços de inventário';
    case RegistrarContagemDeBalancosDeInventario = 'registrar contagem de balanços de inventário';
    case ConcluirBalancosDeInventario = 'concluir balanços de inventário';
    case AdiarBalancosDeInventario = 'adiar balanços de inventário';
    case CancelarBalancosDeInventario = 'cancelar balanços de inventário';
    case IniciarBalancosDeEstoque = 'iniciar balanços de estoque';
    case RegistrarContagemDeBalancosDeEstoque = 'registrar contagem de balanços de estoque';
    case ConcluirBalancosDeEstoque = 'concluir balanços de estoque';
    case AdiarBalancosDeEstoque = 'adiar balanços de estoque';
    case CancelarBalancosDeEstoque = 'cancelar balanços de estoque';

    public function label(): string
    {
        return match ($this) {
            self::ListarAlunos => 'Listar Alunos',
            self::ListarRelatoriosProfessorPorComponenteETurma => 'Listar Relatórios: Professor por Componente e Turma',
            self::ListarRelatoriosComponentesComProfessoresFaltando => 'Listar Relatórios: Componentes com Professores Faltando',
            self::ListarRelatoriosDashboard => 'Listar Relatórios: Dashboard',
            self::ListarTipoManutencao => 'Listar Tipo Manutenção',
            self::ListarTipoStatus => 'Listar Tipo Status',
            self::ListarPedidos => 'Listar Pedidos',
            self::ListarTodosOsPedidos => 'Listar Todos os Pedidos',
            self::ListarEmpresaContratada => 'Listar Empresa Contratada',
            self::ListarEmpresasInativas => 'Listar Empresas Inativas',
            self::ListarUsuarios => 'Listar Usuários',
            self::ListarNiveisDeAcesso => 'Listar Níveis de Acesso',
            self::ListarPermissoesDeExecucao => 'Listar Permissões de Execução',
            self::ListarDominiosDeEmail => 'Listar Dominios de Email',
            self::ListarEscolas => 'Listar Escolas',
            self::ListarTurmas => 'Listar Turmas',
            self::ListarSeries => 'Listar Séries',
            self::ListarProfessores => 'Listar Professores',
            self::ListarFuncoesAdministrativas => 'Listar Funções Administrativas',
            self::ListarAlternativas => 'Listar Alternativas',
            self::ListarPautas => 'Listar Pautas',
            self::ListarAvaliacoes => 'Listar Avaliações',
            self::AcompanharAvaliacoes => 'Acompanhar Avaliações',
            self::VisualizarProgressoPorEscola => 'Visualizar Progresso por Escola',
            self::ListarTiposDeAvaliacoes => 'Listar Tipos de Avaliações',
            self::ListarContratos => 'Listar Contratos',
            self::ListarPedidosMerenda => 'Listar Pedidos: Merenda',
            self::ListarInventarios => 'Listar Inventários',
            self::ListarGestaoDeInventario => 'Listar Gestão de Inventário',
            self::ListarPedidosDeInventario => 'Listar Pedidos de Inventário',
            self::ListarBalancosDeInventario => 'Listar Balanços de Inventário',
            self::ListarGestaoDeEstoque => 'Listar Gestão de Estoque',
            self::ListarBalancosDeEstoque => 'Listar Balanços de Estoque',
            self::ListarGestaoDeMargens => 'Listar Gestão de Margens',
            self::ListarItens => 'Listar Itens',
            self::ListarComponenteCurricular => 'Listar Componente Curricular',
            self::ListarSetores => 'Listar Setores',
            self::ListarServidores => 'Listar Servidores',
            self::ListarPessoas => 'Listar Pessoas',
            self::ListarAvisos => 'Listar Avisos',
            self::ListarEventos => 'Listar Eventos',
            self::ListarEventosTransporte => 'Listar Eventos: Transporte',
            self::ListarEventosGeral => 'Listar Eventos: Geral',
            self::ListarMeusEventos => 'Listar Eventos: Meus Eventos',
            self::ListarReservasVeiculos => 'Listar Reservas de Veículos',
            self::ListarSaldoEleitoral => 'Listar Saldo Eleitoral',

            self::CriarEmpresaContratada => 'Criar Empresa Contratada',
            self::CriarAlunos => 'Criar Alunos',
            self::ImportarAlunosPorPlanilha => 'Importar Alunos por Planilha',
            self::RealizarTransferenciaDeAluno => 'Realizar Transferencia de Aluno',
            self::RealizarRemanejamentoDeAluno => 'Realizar Remanejamento de Aluno',
            self::GerarParecerDeTransferencia => 'Gerar Parecer de Transferencia',
            self::NotificarStatusPendente => 'Notificar Status Pendente',
            self::NotificarImpedimentoDeMatriculaPorFaltaDeTransferencia => 'Notificar Impedimento de Matricula por Falta de Transferencia',
            self::GerenciarImpedimentoDeMatriculaPorFaltaDeTransferencia => 'Gerenciar Impedimento de Matricula por Falta de Transferencia',
            self::CriarTipoManutencao => 'Criar Tipo Manutenção',
            self::CriarTipoStatus => 'Criar Tipo Status',
            self::CriarPedidos => 'Criar Pedidos',
            self::CriarUsuarios => 'Criar Usuários',
            self::CriarNiveisDeAcesso => 'Criar Níveis de Acesso',
            self::CriarPermissoesDeExecucao => 'Criar Permissões de Execução',
            self::CriarDominiosDeEmail => 'Criar Dominios de Email',
            self::CriarSeries => 'Criar Séries',
            self::CriarEscolas => 'Criar Escolas',
            self::CriarTurmas => 'Criar Turmas',
            self::CriarProfessores => 'Criar Professores',
            self::CriarAlternativas => 'Criar Alternativas',
            self::CriarPautas => 'Criar Pautas',
            self::CriarAvaliacoes => 'Criar Avaliações',
            self::CriarFuncoesAdministrativas => 'Criar Funções Administrativas',
            self::CriarTiposDeAvaliacoes => 'Criar Tipos de Avaliações',
            self::CriarContratos => 'Criar Contratos',
            self::CriarPedidosMerenda => 'Criar Pedidos: Merenda',
            self::CriarInventarios => 'Criar Inventários',
            self::CriarPedidosDeInventario => 'Criar Pedidos de Inventário',
            self::CriarBalancosDeInventario => 'Criar Balanços de Inventário',
            self::CriarBalancosDeEstoque => 'Criar Balanços de Estoque',
            self::CriarItens => 'Criar Itens',
            self::CriarComponenteCurricular => 'Criar Componente Curricular',
            self::CriarSetores => 'Criar Setores',
            self::CriarServidores => 'Criar Servidores',
            self::CriarPessoas => 'Criar Pessoas',
            self::CriarAvisos => 'Criar Avisos',
            self::CriarEventos => 'Criar Eventos',
            self::CriarEventosTransporte => 'Criar Eventos: Transporte',
            self::CriarReservasVeiculos => 'Criar Reservas de Veículos',
            self::SolicitarAdicaoSaldoEleitoral => 'Solicitar Adição de Saldo Eleitoral',
            self::SolicitarUsoSaldoEleitoral => 'Solicitar Uso de Saldo Eleitoral',
            self::GerenciarSaldoEleitoral => 'Gerenciar Saldo Eleitoral',

            self::EditarEmpresaContratada => 'Editar Empresa Contratada',
            self::EditarAlunos => 'Editar Alunos',
            self::EditarPedidos => 'Editar Pedidos',
            self::EditarCamposDaEscola => 'Editar Campos da Escola',
            self::EditarCodigoDaEscola => 'Editar Codigo da Escola',
            self::EditarEscolaDoAluno => 'Editar Escola do Aluno',
            self::EditarEscolaDaTurma => 'Editar Escola da Turma',
            self::EditarEscolaDoUsuario => 'Editar Escola do Usuario',
            self::EditarEscolaDoProfessor => 'Editar Escola do Professor',
            self::EditarMatriculaDoProfessor => 'Editar Matricula do Professor',
            self::EditarNomeDoProfessor => 'Editar Nome do Professor',
            self::EditarEspecializacoesDeProfessores => 'Editar Especializações de Professores',
            self::EditarDadosDaTurma => 'Editar Dados da Turma',
            self::EditarTurmas => 'Editar Turmas',
            self::EditarTipoManutencao => 'Editar Tipo Manutenção',
            self::EditarTipoStatus => 'Editar Tipo Status',
            self::EditarSetorDoUsuario => 'Editar Setor do Usuário',
            self::EditarUsuarios => 'Editar Usuários',
            self::RedefinirSenhasDeUsuarios => 'Redefinir Senhas de Usuários',
            self::EditarNiveisDeAcesso => 'Editar Níveis de Acesso',
            self::EditarPermissoesDeExecucao => 'Editar Permissões de Execução',
            self::EditarDominiosDeEmail => 'Editar Dominios de Email',
            self::EditarSeries => 'Editar Séries',
            self::EditarEscolas => 'Editar Escolas',
            self::GerenciarLotacoes => 'Gerenciar Lotações',
            self::EditarProfessores => 'Editar Professores',
            self::EditarFuncoesAdministrativas => 'Editar Funções Administrativas',
            self::EditarAlternativas => 'Editar Alternativas',
            self::EditarPautas => 'Editar Pautas',
            self::EditarAvaliacoes => 'Editar Avaliações',
            self::EditarTiposDeAvaliacoes => 'Editar Tipos de Avaliações',
            self::EditarContratos => 'Editar Contratos',
            self::EditarPedidosMerenda => 'Editar Pedidos: Merenda',
            self::EditarItens => 'Editar Itens',
            self::EditarComponenteCurricular => 'Editar Componente Curricular',
            self::EditarDadosDoProfessor => 'Editar Dados do Professor',
            self::EditarSetores => 'Editar Setores',
            self::EditarServidores => 'Editar Servidores',
            self::EditarPessoas => 'Editar Pessoas',
            self::EditarDadosDePessoas => 'Editar Dados de Pessoas',
            self::EditarTurmasEComponentesDePessoas => 'Editar Turmas e Componentes de Pessoas',
            self::EditarAvisos => 'Editar Avisos',
            self::EditarEventos => 'Editar Eventos',
            self::EditarReservasVeiculos => 'Editar Reservas de Veículos',

            self::GerenciarFuncoesDeServidores => 'Gerenciar Funções de Servidores',
            self::GerenciarVinculosEstruturaisDePessoas => 'Gerenciar Vínculos Estruturais de Pessoas',
            self::GerenciarPublicoAlvoDeAvisos => 'Gerenciar Público-alvo de Avisos',
            self::GerenciarPublicoAlvoDeEventos => 'Gerenciar Público-alvo de Eventos',
            self::GerenciarTransporteDeEventos => 'Gerenciar Transporte de Eventos',
            self::GerenciarFrotaVeiculos => 'Gerenciar Frota de Veículos',
            self::CancelarReservasVeiculos => 'Cancelar Reservas de Veículos',
            self::TransferirProfessores => 'Transferir Professores',
            self::DesativarProfessores => 'Desativar Professores',
            self::DesativarEventos => 'Desativar Eventos',
            self::DesativarEventosTransporte => 'Desativar Eventos: Transporte',
            self::RejeitarEventosTransporte => 'Rejeitar Eventos: Transporte',

            self::ExcluirEmpresaContratada => 'Excluir Empresa Contratada',
            self::ExcluirAlunos => 'Excluir Alunos',
            self::ExcluirTipoManutencao => 'Excluir Tipo Manutenção',
            self::ExcluirTipoStatus => 'Excluir Tipo Status',
            self::ExcluirPedidos => 'Excluir Pedidos',
            self::ExcluirUsuarios => 'Excluir Usuários',
            self::ExcluirNiveisDeAcesso => 'Excluir Níveis de Acesso',
            self::ExcluirPermissoesDeExecucao => 'Excluir Permissões de Execução',
            self::ExcluirDominiosDeEmail => 'Excluir Dominios de Email',
            self::ExcluirSeries => 'Excluir Séries',
            self::ExcluirEscolas => 'Excluir Escolas',
            self::ExcluirTurmas => 'Excluir Turmas',
            self::ExcluirProfessores => 'Excluir Professores',
            self::ExcluirAlternativas => 'Excluir Alternativas',
            self::ExcluirPautas => 'Excluir Pautas',
            self::ExcluirAvaliacoes => 'Excluir Avaliações',
            self::ExcluirFuncoesAdministrativas => 'Excluir Funções Administrativas',
            self::ExcluirTiposDeAvaliacoes => 'Excluir Tipos de Avaliações',
            self::ExcluirContratos => 'Excluir Contratos',
            self::ExcluirSetores => 'Excluir Setores',
            self::ExcluirServidores => 'Excluir Servidores',
            self::ExcluirPessoas => 'Excluir Pessoas',
            self::ExcluirPessoasDefinitivamente => 'Excluir Pessoas Definitivamente',
            self::ExcluirComponenteCurricular => 'Excluir Componente Curricular',
            self::ExcluirPedidosMerenda => 'Excluir Pedidos: Merenda',
            self::ExcluirItens => 'Excluir Itens',
            self::ExcluirEmpresaContratadaEmMassa => 'Excluir Empresa Contratada em Massa',
            self::ExcluirAlunosEmMassa => 'Excluir Alunos em Massa',
            self::ExcluirTurmasEmMassa => 'Excluir Turmas em Massa',
            self::ExcluirProfessoresEmMassa => 'Excluir Professores em Massa',
            self::ExcluirTiposDeManutencaoEmMassa => 'Excluir Tipos de Manutenção em Massa',
            self::ExcluirTipoStatusEmMassa => 'Excluir Tipo Status em Massa',
            self::ExcluirPedidosEmMassa => 'Excluir Pedidos em Massa',
            self::ExcluirAlternativasEmMassa => 'Excluir Alternativas em Massa',
            self::ExcluirFuncoesAdministrativasEmMassa => 'Excluir Funções Administrativas em Massa',
            self::ExcluirTiposDeAvaliacoesEmMassa => 'Excluir Tipos de Avaliações em Massa',
            self::ExcluirSetoresEmMassa => 'Excluir Setores em Massa',
            self::ExcluirItensEmMassa => 'Excluir Itens em Massa',
            self::ExcluirAvisos => 'Excluir Avisos',
            self::ExcluirEventos => 'Excluir Eventos',

            self::ExportarAlunos => 'Exportar Alunos',
            self::ExportarModeloDeImportacaoDeAlunos => 'Exportar Modelo de Importacao de Alunos',
            self::ExportarTurmas => 'Exportar Turmas',
            self::ExportarEscolas => 'Exportar Escolas',
            self::ExportarRelatorios => 'Exportar Relatórios',
            self::ExportarAvaliacoes => 'Exportar Avaliações',
            self::ExportarProfessores => 'Exportar Professores',
            self::ExportarArquivosPedido => 'Exportar Arquivos Pedido',
            self::ExportarComponenteCurricular => 'Exportar Componente Curricular',
            self::ExportarModeloDeImportacaoDeEventos => 'Exportar Modelo de Importação de Eventos',
            self::ImportarEventosPorPlanilha => 'Importar Eventos por Planilha',

            self::VisualizarDetalhesDeAluno => 'Visualizar Detalhes de Aluno',
            self::VisualizarProfessores => 'Visualizar Professores',
            self::VisualizarUsuariosOnline => 'Visualizar Usuarios Online',
            self::VisualizarSelectDePerfis => 'Visualizar Select de Perfis',
            self::VisualizarNotificacoes => 'Visualizar Notificações',
            self::CriarNotificacoes => 'Criar Notificações',
            self::EnviarNotificacoesTodosOsUsuarios => 'Enviar Notificações: Todos os Usuários',
            self::EnviarNotificacoesUsuariosEspecificos => 'Enviar Notificações: Usuários Específicos',
            self::EnviarNotificacoesNiveisDeAcesso => 'Enviar Notificações: Níveis de Acesso',
            self::EnviarNotificacoesUsuariosPorEscola => 'Enviar Notificações: Usuários por Escola',
            self::EnviarNotificacoesProfessoresPorTurma => 'Enviar Notificações: Professores por Turma',
            self::EnviarNotificacoesUsuariosPorPermissao => 'Enviar Notificações: Usuários por Permissão',
            self::EnviarNotificacoesSetorEspecifico => 'Enviar Notificações: Setor Específico',
            self::VisualizarEspecializacoesDeProfessores => 'Visualizar Especializações de Professores',
            self::VisualizarDetalhesDeProfessor => 'Visualizar Detalhes de Professor',
            self::VisualizarSetorDoUsuario => 'Visualizar Setor do Usuário',
            self::VisualizarStatusEncaminhadoAoSetor => 'Visualizar Status: Encaminhado ao Setor',
            self::VisualizarHistoricoDePedidos => 'Visualizar Histórico de Pedidos',
            self::VisualizarArquivosDePedidos => 'Visualizar Arquivos de Pedidos',
            self::VisualizarPedidosPorStatus => 'Visualizar Pedidos por Status',
            self::VisualizarPainelPersonalizado => 'Visualizar Painel Personalizado',
            self::VisualizarFeedbackDePedidos => 'Visualizar Feedback de Pedidos',
            self::VisualizarNotificacaoVencimentoDePedidos => 'Visualizar Notificação: Vencimento de Pedidos',
            self::VisualizarNotificacaoPedidosAtrasados => 'Visualizar Notificação: Pedidos Atrasados',
            self::VisualizarNotificacaoPedidosEmergenciais => 'Visualizar Notificação: Pedidos Emergenciais',
            self::VisualizarNotificacaoPedidoReaberto => 'Visualizar Notificação: Pedido Reaberto',
            self::VisualizarNotificacaoPedidoAdicionalCriado => 'Visualizar Notificação: Pedido Adicional Criado',
            self::VisualizarNotificacaoBalancoDeEstoque => 'Visualizar Notificação: Balanço de Estoque',
            self::VisualizarTelaDeInicio => 'Visualizar Tela de Inicio',
            self::VisualizarAgendaDeTodaARede => 'Visualizar Agenda de Toda a Rede',
            self::PublicarAvisos => 'Publicar Avisos',
            self::PublicarEventos => 'Publicar Eventos',
            self::PublicarEventosTransporte => 'Publicar Eventos: Transporte',

            self::AcessarEscopoGlobalDeSetores => 'Acessar Escopo Global de Setores',
            self::BaixarApp => 'Baixar App',

            self::FiltrarAlunosPorEscola => 'Filtrar Alunos por Escola',
            self::FiltrarProfessoresPorEscola => 'Filtrar Professores por Escola',
            self::FiltrarProfessoresPorComponente => 'Filtrar Professores por Componente',
            self::FiltrarProfessoresPorSerie => 'Filtrar Professores por Serie',
            self::FiltrarTurmasPorEscola => 'Filtrar Turmas por Escola',

            self::AplicarPermissoes => 'Aplicar Permissoes',
            self::AvaliarPedidos => 'Avaliar Pedidos',
            self::ComentarPedidos => 'Comentar Pedidos',
            self::EncaminharPedidosParaSetor => 'Encaminhar Pedidos para Setor',
            self::EnviarPedidosParaEmpresa => 'Enviar Pedidos para Empresa',
            self::VincularPedidosAdicionais => 'Vincular Pedidos Adicionais',
            self::ResponderAvaliacoes => 'Responder Avaliações',
            self::PreencherAvaliacoesEmMassa => 'Preencher Avaliações em Massa',
            self::ConcluirAvaliacoes => 'Concluir Avaliações',
            self::ReabrirAvaliacoes => 'Reabrir Avaliações',
            self::AprovarPedidosDeInventario => 'Aprovar Pedidos de Inventário',
            self::GerarRomaneiosDeInventario => 'Gerar Romaneios de Inventário',
            self::ConferirPedidosDeInventario => 'Conferir Pedidos de Inventário',
            self::IniciarBalancosDeInventario => 'Iniciar Balanços de Inventário',
            self::RegistrarContagemDeBalancosDeInventario => 'Registrar Contagem de Balanços de Inventário',
            self::ConcluirBalancosDeInventario => 'Concluir Balanços de Inventário',
            self::AdiarBalancosDeInventario => 'Adiar Balanços de Inventário',
            self::CancelarBalancosDeInventario => 'Cancelar Balanços de Inventário',
            self::IniciarBalancosDeEstoque => 'Iniciar Balanços de Estoque',
            self::RegistrarContagemDeBalancosDeEstoque => 'Registrar Contagem de Balanços de Estoque',
            self::ConcluirBalancosDeEstoque => 'Concluir Balanços de Estoque',
            self::AdiarBalancosDeEstoque => 'Adiar Balanços de Estoque',
            self::CancelarBalancosDeEstoque => 'Cancelar Balanços de Estoque',
        };
    }
}
