services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app-gestao-edu
    container_name: laravel-app-gestao-edu
    working_dir: /var/www
    ports:
      - "8020:8020"
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_gestao-edu

  cron:
    image: laravel-app-gestao-edu
    container_name: laravel-cron-gestao-edu
    working_dir: /var/www
    entrypoint: []
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_gestao-edu
  db:
    image: mysql:8.0
    container_name: laravel-db-gestao-edu
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao-edu
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - laravel_gestao-edu

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin-gestao-edu
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_gestao-edu

  redis:
    image: redis:7
    container_name: laravel-redis-gestao-edu
    ports:
      - "6381:6379"
    networks:
      - laravel_gestao-edu

volumes:
  db_data:
  vendor:
  node_modules:


networks:
  laravel_gestao-edu:
    driver: bridge
