-- Hub de testes: pautas do 3o ano. Uma unica instrucao; IDs explicitos e idempotentes.
INSERT INTO pautas
    (id, tipo_avaliacao_id, texto, componente_curricular_id, serie_id, status, created_at, updated_at)
VALUES
    (123, 2, 'Identifica diferentes formatos do teatro de bonecos.', 6, 7, 1, NOW(), NOW()),
    (124, 2, 'Identifica obras do pintor Abraão Hachicho.', 6, 7, 1, NOW(), NOW()),
    (125, 2, 'Brinca e se expressa utilizando o teatro de bonecos de forma criativa.', 6, 7, 1, NOW(), NOW()),
    (126, 2, 'Identifica obras e características da pintura realista.', 6, 7, 1, NOW(), NOW()),
    (127, 2, 'Reconhece algumas danças realizadas em pares.', 6, 7, 1, NOW(), NOW()),
    (128, 2, 'Reconhece valores necessários para o bom andamento da dança em par, como respeito, cooperação e sintonia.', 6, 7, 1, NOW(), NOW()),
    (155, 2, 'Expressa-se oralmente nos jogos de dramatização.', 7, 7, 1, NOW(), NOW()),
    (156, 2, 'Expressa-se corporalmente nos jogos de dramatização.', 7, 7, 1, NOW(), NOW()),
    (157, 2, 'Experimenta e frui danças do contexto local e regional.', 7, 7, 1, NOW(), NOW()),
    (158, 2, 'Identifica a esquerda e direita no seu corpo.', 7, 7, 1, NOW(), NOW()),
    (159, 2, 'Identifica a esquerda e direita no outro.', 7, 7, 1, NOW(), NOW()),
    (160, 2, 'Reconhece o esporte Handebol nos jogos pré-desportivos.', 7, 7, 1, NOW(), NOW()),
    (161, 2, 'Participa dos jogos pré-desportivos utilizando os fundamentos básicos do handebol (usar as mãos para manipular a bola; arremesso; passe e drible).', 7, 7, 1, NOW(), NOW()),
    (162, 2, 'Joga o jogo de damas.', 7, 7, 1, NOW(), NOW()),
    (164, 2, 'Participa do esporte bocha respeitando seus elementos (lançar as bolas de uma área determinada; fazer com que as bolas se aproximem do “bolim” que estará em um ponto determinado aleatoriamente).', 7, 7, 1, NOW(), NOW()),
    (165, 2, 'Reconhece o esporte Basquetebol nos jogos pré-desportivos.', 7, 7, 1, NOW(), NOW()),
    (166, 2, 'Participa dos jogos pré-desportivos utilizando os fundamentos básicos do basquetebol (usar as mãos para manipular a bola; arremesso; passe e drible).', 7, 7, 1, NOW(), NOW()),
    (342, 2, 'Identifica características do modo de vida da população Xetá.', 3, 7, 1, NOW(), NOW()),
    (343, 2, 'Reconhece o povo indígena Xetá e outros grupos sociais e étnicos como parte da formação histórica, cultural e social do lugar onde vive.', 3, 7, 1, NOW(), NOW()),
    (344, 2, 'Identifica algumas formas de lazer realizadas na cidade e no campo.', 3, 7, 1, NOW(), NOW()),
    (345, 2, 'Reconhece diferentes formas de lazer realizadas no campo.', 3, 7, 1, NOW(), NOW()),
    (346, 2, 'Identifica atividades relacionadas à natureza e ao modo de vida em espaços rurais.', 3, 7, 1, NOW(), NOW()),
    (347, 2, 'Reconhece diferentes manifestações culturais, como festas, brincadeiras, museus e gastronomia.', 3, 7, 1, NOW(), NOW()),
    (348, 2, 'Identifica a importância das manifestações culturais para a história, a memória e a identidade dos grupos sociais.', 3, 7, 1, NOW(), NOW()),
    (370, 2, 'Reconhece os números de 1 a 20 em inglês oralmente', 8, 7, 1, NOW(), NOW()),
    (371, 2, 'Reconhece oralmente comandos e expressões relacionados às regras da turma em inglês.', 8, 7, 1, NOW(), NOW()),
    (372, 2, 'Compreende palavras e expressões simples em inglês em atividades de escuta e oralidade.', 8, 7, 1, NOW(), NOW()),
    (373, 2, 'Relaciona imagens ao vocabulário de animais em inglês.', 8, 7, 1, NOW(), NOW()),
    (374, 2, 'Reconhece e relaciona os dias da semana ao contexto do calendário escolar.', 8, 7, 1, NOW(), NOW()),
    (375, 2, 'Reconhece e relaciona objetos da sala de aula à imagem e ao vocabulário correspondente em inglês.', 8, 7, 1, NOW(), NOW()),
    (436, 2, 'Reconhece características do modo como os animais se deslocam.', 5, 7, 1, NOW(), NOW()),
    (437, 2, 'Reconhece características do modo como os animais se alimentam.', 5, 7, 1, NOW(), NOW()),
    (438, 2, 'Reconhece características do modo como os animais se reproduzem.', 5, 7, 1, NOW(), NOW()),
    (439, 2, 'Identifica fases do ciclo de vida de animais.', 5, 7, 1, NOW(), NOW()),
    (440, 2, 'Identifica alterações do corpo de animais que passam por metamorfose.', 5, 7, 1, NOW(), NOW()),
    (441, 2, 'Identifica o corpo humano em suas diferentes fases de desenvolvimento.', 5, 7, 1, NOW(), NOW()),
    (442, 2, 'Identifica diferentes tipos de paisagem na superfície terrestre.', 4, 7, 1, NOW(), NOW()),
    (443, 2, 'Identifica elementos que compõem a paisagem natural e cultural.', 4, 7, 1, NOW(), NOW()),
    (444, 2, 'Lê texto em voz alta com fluência.', 1, 7, 1, NOW(), NOW()),
    (445, 2, 'Reconhece o assunto do texto lido', 1, 7, 1, NOW(), NOW()),
    (446, 2, 'Reconhece o gênero textual.', 1, 7, 1, NOW(), NOW()),
    (447, 2, 'Identifica a finalidade do texto.', 1, 7, 1, NOW(), NOW()),
    (448, 2, 'Identifica informações explícitas em texto lido.', 1, 7, 1, NOW(), NOW()),
    (449, 2, 'Infere uma informação do texto lido.', 1, 7, 1, NOW(), NOW()),
    (450, 2, 'Escreve o nome completo.', 1, 7, 1, NOW(), NOW()),
    (451, 2, 'Produz, individualmente, conto, considerando os elementos da narrativa.', 1, 7, 1, NOW(), NOW()),
    (452, 2, 'Escrever números convencionalmente, compreendendo o princípio de valor posicional dos números no Sistema de Numeração Decimal (SND).', 2, 7, 1, NOW(), NOW()),
    (453, 2, 'Lê números entre 1 e 5 000.', 2, 7, 1, NOW(), NOW()),
    (454, 2, 'Escreve números entre 1 e 5 000.', 2, 7, 1, NOW(), NOW()),
    (455, 2, 'Calcula adição com números de 2 ordens, sem agrupamento, utilizando o algoritmo.', 2, 7, 1, NOW(), NOW()),
    (456, 2, 'Calcula adição com números de 3 ordens, sem agrupamento, utilizando o algoritmo.', 2, 7, 1, NOW(), NOW()),
    (457, 2, 'Resolve situações-problema de adição que demandam a ideia de juntar, com registro por meio de algoritmo.', 2, 7, 1, NOW(), NOW()),
    (458, 2, 'Resolve situações-problema de adição, que demandam a ideia de acrescentar, com registro por meio de algoritmo.', 2, 7, 1, NOW(), NOW()),
    (519, 2, 'Grafa palavras utilizando regras de correspondência fonema-grafema regulares diretas e contextuais (palavras com r/rr. s/ss).', 1, 7, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    updated_at = IF(tipo_avaliacao_id <> VALUES(tipo_avaliacao_id)
        OR NOT (texto <=> VALUES(texto))
        OR componente_curricular_id <> VALUES(componente_curricular_id)
        OR serie_id <> VALUES(serie_id)
        OR status <> VALUES(status), NOW(), updated_at),
    tipo_avaliacao_id = VALUES(tipo_avaliacao_id),
    texto = VALUES(texto),
    componente_curricular_id = VALUES(componente_curricular_id),
    serie_id = VALUES(serie_id),
    status = VALUES(status);

