-- Hub de testes: pautas do 4o ano. Uma unica instrucao; IDs explicitos e idempotentes.
INSERT INTO pautas
    (id, tipo_avaliacao_id, texto, componente_curricular_id, serie_id, status, created_at, updated_at)
VALUES
    (129, 2, 'Diferencia as técnicas de alto-relevo e baixo-relevo em produções artísticas.', 6, 8, 1, NOW(), NOW()),
    (130, 2, 'Reconhece diferentes manifestações das artes cênicas, como teatro, dança e ópera.', 6, 8, 1, NOW(), NOW()),
    (131, 2, 'Reconhece elementos que compõem uma arte cênica, como personagens, cenário, figurino, movimentos e expressão corporal.', 6, 8, 1, NOW(), NOW()),
    (132, 2, 'Reconhece características das obras de Tarsila do Amaral.', 6, 8, 1, NOW(), NOW()),
    (133, 2, 'Relaciona obras de arte ao contexto histórico e cultural em que foram produzidas.', 6, 8, 1, NOW(), NOW()),
    (134, 2, 'Compreende o conceito de estilo artístico nas artes visuais.', 6, 8, 1, NOW(), NOW()),
    (135, 2, 'Identifica características da escrita musical antiga e da notação musical atual.', 6, 8, 1, NOW(), NOW()),
    (167, 2, 'Realiza os movimentos relacionados à ginástica circense.', 7, 8, 1, NOW(), NOW()),
    (168, 2, 'Experimenta e frui danças do contexto brasileiro.', 7, 8, 1, NOW(), NOW()),
    (169, 2, 'Reconhece o esporte Handebol nos jogos pré-desportivos.', 7, 8, 1, NOW(), NOW()),
    (170, 2, 'Participa dos jogos pré-desportivos utilizando os fundamentos básicos do handebol (usar as mãos para manipular a bola; arremesso; passe e drible).', 7, 8, 1, NOW(), NOW()),
    (171, 2, 'Joga o jogo de damas respeitando as suas regras.', 7, 8, 1, NOW(), NOW()),
    (172, 2, 'Participa do esporte atletismo – lançamentos e arremessos - respeitando seus elementos básicos (realizar o lançamento do objeto de dentro da área estabelecida; lançar o objeto o mais longe possível).', 7, 8, 1, NOW(), NOW()),
    (173, 2, 'Participa do esporte da categoria campo e taco - respeitando seus elementos básicos (rebater uma bola lançada pelo adversário o mais longe possível; percorrer o maior número de vezes as bases ou a maior distância entre as bases.).', 7, 8, 1, NOW(), NOW()),
    (349, 2, 'Reconhece a importância das novas tecnologias e das rotas comerciais.', 3, 8, 1, NOW(), NOW()),
    (350, 2, 'Reconhece a importância dos caminhos terrestres, fluviais e marítimos.', 3, 8, 1, NOW(), NOW()),
    (351, 2, 'Identifica o papel de Portugal e Espanha nas Grandes Navegações.', 3, 8, 1, NOW(), NOW()),
    (352, 2, 'Reconhece as rotas marítimas como importantes para a circulação de mercadorias, pessoas e culturas, bem como para as transformações da vida social e comercial.', 3, 8, 1, NOW(), NOW()),
    (376, 2, 'Identifica comandos e instruções comuns do cotidiano escolar em língua inglesa.', 8, 8, 1, NOW(), NOW()),
    (377, 2, 'Reconhece e nomeia os dias da semana.', 8, 8, 1, NOW(), NOW()),
    (378, 2, 'Reconhece e nomeia os meses do ano.', 8, 8, 1, NOW(), NOW()),
    (379, 2, 'Reconhece alguns esportes em inglês.', 8, 8, 1, NOW(), NOW()),
    (380, 2, 'Reconhece algumas profissões em inglês.', 8, 8, 1, NOW(), NOW()),
    (381, 2, 'Utiliza estruturas simples para identificar profissões (He’s a… / She’s a…).', 8, 8, 1, NOW(), NOW()),
    (382, 2, 'Participa de interações orais simples em língua inglesa.', 8, 8, 1, NOW(), NOW()),
    (459, 2, 'Identifica o papel dos fungos e bactérias no processo de decomposição.', 5, 8, 1, NOW(), NOW()),
    (460, 2, 'Relaciona a atuação de microrganismos a algumas doenças humanas.', 5, 8, 1, NOW(), NOW()),
    (461, 2, 'Identifica atitudes e medidas para prevenir doenças transmitidas por microrganismos.', 5, 8, 1, NOW(), NOW()),
    (462, 2, 'Reconhece a importância econômica e ecológica de diferentes microrganismos.', 5, 8, 1, NOW(), NOW()),
    (463, 2, 'Cria e simula algoritmos utilizando sequência, repetição e condição.', 20, 8, 1, NOW(), NOW()),
    (464, 2, 'Reconhece formas de organização e representação de dados (listas, grafos e matrizes).', 20, 8, 1, NOW(), NOW()),
    (465, 2, 'Localiza a Unidade de Federação - UF onde vive no mapa do Brasil, bem como sua capital.', 4, 8, 1, NOW(), NOW()),
    (466, 2, 'Reconhece diferentes tipos de divisão política dos territórios (estados, regiões, regiões metropolitanas, municípios, bairros).', 4, 8, 1, NOW(), NOW()),
    (467, 2, 'Identifica os países que fazem fronteira com a Unidade de Federação onde vive no mapa, bem como a fronteira marítima.', 4, 8, 1, NOW(), NOW()),
    (468, 2, 'Lê texto em voz alta com fluência.', 1, 8, 1, NOW(), NOW()),
    (469, 2, 'Reconhece o assunto do texto.', 1, 8, 1, NOW(), NOW()),
    (470, 2, 'Reconhece o gênero textual.', 1, 8, 1, NOW(), NOW()),
    (471, 2, 'Identifica a finalidade de um texto.', 1, 8, 1, NOW(), NOW()),
    (472, 2, 'Localiza informações explícitas em texto.', 1, 8, 1, NOW(), NOW()),
    (473, 2, 'Infere o sentido de palavras ou expressões desconhecidas em textos, com base no contexto da frase ou do texto.', 1, 8, 1, NOW(), NOW()),
    (474, 2, 'Infere informações implícitas nos textos lidos.', 1, 8, 1, NOW(), NOW()),
    (475, 2, 'Estabelece relações entre partes de um texto, identificando substituições lexicais (de substantivo por sinônimos) ou pronominais (uso de pronomes anafóricos – pessoais, possessivos, demonstrativos) que contribuem para a continuidade do texto.', 1, 8, 1, NOW(), NOW()),
    (476, 2, 'Grafa palavras utilizando regras de correspondência fonema-grafema regulares diretas e contextuais (palavras terminadas em -ação, -essão ou -issão, -aço ou -aça).', 1, 8, 1, NOW(), NOW()),
    (477, 2, 'Produz notícias sobre fatos ocorridos no universo escolar.', 1, 8, 1, NOW(), NOW()),
    (478, 2, 'Utilizar adequadamente os sinais de pontuação na escrita de textos.', 1, 8, 1, NOW(), NOW()),
    (479, 2, 'Ler números naturais entre 1 e 30 000.', 2, 8, 1, NOW(), NOW()),
    (480, 2, 'Escrever números naturais entre 1 e 30 000.', 2, 8, 1, NOW(), NOW()),
    (481, 2, 'Identifica eventos aleatórios cotidianos.', 2, 8, 1, NOW(), NOW()),
    (482, 2, 'Lê dados contidos em tabela simples e de dupla entrada.', 2, 8, 1, NOW(), NOW()),
    (483, 2, 'Calcular multiplicação até a unidade de milhar no multiplicando e unidade no multiplicador.', 2, 8, 1, NOW(), NOW()),
    (484, 2, 'Resolve situações-problema de multiplicação com a ideia de configuração retangular.', 2, 8, 1, NOW(), NOW()),
    (485, 2, 'Resolve situações-problema de multiplicação que demandam a ideia de comparação entre razões (proporcionalidade), com registro por meio de algoritmo.', 2, 8, 1, NOW(), NOW()),
    (486, 2, 'Resolve situações-problema de multiplicação que demandam a ideia de análise combinatória, com registro por meio de algoritmo.', 2, 8, 1, NOW(), NOW()),
    (487, 2, 'Calcula a duração de um intervalo de tempo.', 2, 8, 1, NOW(), NOW()),
    (488, 2, 'Identifica a temperatura máxima e mínima diárias em sua cidade, da região ou estado.', 2, 8, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    updated_at = IF(tipo_avaliacao_id <> VALUES(tipo_avaliacao_id)
        OR NOT (texto <=> VALUES(texto))
        OR componente_curricular_id <> VALUES(componente_curricular_id)
        OR serie_id <> VALUES(serie_id)
        OR status <> VALUES(status), NOW(), updated_at),
    tipo_avaliacao_id = VALUES(tipo_avaliacao_id),
    texto = VALUES(texto),
    componente_curricular_id = VALUES(componente_curricular_id),
    serie_id = VALUES(serie_id),
    status = VALUES(status);

