-- Hub de testes: pautas do 5o ano. Uma unica instrucao; IDs explicitos e idempotentes.
INSERT INTO pautas
    (id, tipo_avaliacao_id, texto, componente_curricular_id, serie_id, status, created_at, updated_at)
VALUES
    (136, 2, 'Realiza composições artísticas utilizando a técnica do pontilhismo com organização e criatividade.', 6, 9, 1, NOW(), NOW()),
    (137, 2, 'Identifica elementos da Op Art em diferentes produções artísticas.', 6, 9, 1, NOW(), NOW()),
    (138, 2, 'Identifica diferenças entre arte artesanal e produção industrial.', 6, 9, 1, NOW(), NOW()),
    (139, 2, 'Demonstra criatividade e organização na elaboração do projeto da cadeira.', 6, 9, 1, NOW(), NOW()),
    (140, 2, 'Reconhece a dança como linguagem artística presente no cinema.', 6, 9, 1, NOW(), NOW()),
    (174, 2, 'Coopera com os outros alunos para obter sucesso, considerando-os como parceiros e não como adversários.', 7, 9, 1, NOW(), NOW()),
    (175, 2, 'Organiza o corpo no tempo e espaço na dança circular.', 7, 9, 1, NOW(), NOW()),
    (176, 2, 'Conhece algumas regras do esporte handebol (não usar os pés; fazer gol na baliza adversária; a partida é disputada dentro de um espaço determinado; apenas o goleiro pode ficar dentro da área).', 7, 9, 1, NOW(), NOW()),
    (177, 2, 'Utiliza os fundamentos básicos do esporte handebol (empunhadura; recepção; arremesso; passe; drible e passos) nas atividades.', 7, 9, 1, NOW(), NOW()),
    (178, 2, 'Participa do esporte da categoria rede/parede - respeitando seus elementos básicos (arremessar, lançar ou rebater a bola em direção a setores da quadra adversária nos quais o rival seja incapaz de devolvê-la ou que leve o adversário a cometer um erro dentro do período de tempo em que o objeto do jogo está em movimento).', 7, 9, 1, NOW(), NOW()),
    (179, 2, 'Participa do esporte atletismo – lançamento e arremesso - respeitando seus elementos básicos (lançar ou arremessar o objeto com ou sem corrida; realizar o lançamento do objeto de dentro da área estabelecida; lançar o objeto o mais longe possível).', 7, 9, 1, NOW(), NOW()),
    (180, 2, 'Participa do esporte da categoria campo e taco - respeitando seus elementos básicos (rebater uma bola lançada pelo adversário o mais longe possível; percorrer o maior número de vezes as bases ou a maior distância entre as bases.).', 7, 9, 1, NOW(), NOW()),
    (353, 2, 'Identifica a organização política do Egito Antigo.', 3, 9, 1, NOW(), NOW()),
    (354, 2, 'Reconhece o papel das culturas e das religiões na composição identitária dos povos antigos.', 3, 9, 1, NOW(), NOW()),
    (355, 2, 'Reconhece aspectos da organização política da Grécia Antiga.', 3, 9, 1, NOW(), NOW()),
    (356, 2, 'Identifica a importância das cidades-Estado, da cidadania e da participação social para a formação da ideia de Estado.', 3, 9, 1, NOW(), NOW()),
    (357, 2, 'Reconhece elementos da cultura e da religião grega, identificando sua importância para a formação da identidade e dos modos de vida do povo grego na Antiguidade.', 3, 9, 1, NOW(), NOW()),
    (383, 2, 'Compreende e responde a comandos e instruções simples do cotidiano escolar em língua inglesa.', 8, 9, 1, NOW(), NOW()),
    (384, 2, 'Utiliza a estrutura simples I like… para expressar preferências.', 8, 9, 1, NOW(), NOW()),
    (385, 2, 'Reconhece e nomeia vocabulário relacionado à alimentação em inglês.', 8, 9, 1, NOW(), NOW()),
    (386, 2, 'Reconhece e nomeia números em inglês de 1 a 100.', 8, 9, 1, NOW(), NOW()),
    (387, 2, 'Reconhece alimentos em inglês.', 8, 9, 1, NOW(), NOW()),
    (388, 2, 'Utiliza estruturas simples para expressar preferências (I like… / I don’t like…).', 8, 9, 1, NOW(), NOW()),
    (389, 2, 'Responde oralmente a perguntas simples sobre preferências (Do you like…?).', 8, 9, 1, NOW(), NOW()),
    (489, 2, 'Relaciona os diferentes tipos de nutrientes à sua função no organismo.', 5, 9, 1, NOW(), NOW()),
    (490, 2, 'Identifica hábitos saudáveis de alimentação.', 5, 9, 1, NOW(), NOW()),
    (491, 2, 'Reconhece os níveis de organização do corpo humano (células, tecidos, órgãos, sistemas e organismos).', 5, 9, 1, NOW(), NOW()),
    (492, 2, 'Cria e simula algoritmos utilizando sequência, repetição e condição.', 20, 9, 1, NOW(), NOW()),
    (493, 2, 'Reconhece formas de organização e representação de dados (listas, grafos e matrizes).', 20, 9, 1, NOW(), NOW()),
    (494, 2, 'Reconhece as características do espaço urbano brasileiro.', 4, 9, 1, NOW(), NOW()),
    (495, 2, 'Reconhece os diversos usos do espaço urbano.', 4, 9, 1, NOW(), NOW()),
    (496, 2, 'Compreende o processo de urbanização.', 4, 9, 1, NOW(), NOW()),
    (497, 2, 'Identifica transformações na paisagem a partir de diferentes representações.', 4, 9, 1, NOW(), NOW()),
    (498, 2, 'Analisa diferentes mapas temáticos.', 4, 9, 1, NOW(), NOW()),
    (499, 2, 'Compreende a ocorrência de problemas ambientais característicos de áreas rurais.', 4, 9, 1, NOW(), NOW()),
    (500, 2, 'Compreende a ocorrência de problemas ambientais característicos de áreas urbanas.', 4, 9, 1, NOW(), NOW()),
    (501, 2, 'Lê texto em voz alta com fluência.', 1, 9, 1, NOW(), NOW()),
    (502, 2, 'Identifica o assunto do texto lido.', 1, 9, 1, NOW(), NOW()),
    (503, 2, 'Identifica o gênero textual.', 1, 9, 1, NOW(), NOW()),
    (504, 2, 'Identifica a finalidade de um texto.', 1, 9, 1, NOW(), NOW()),
    (505, 2, 'Localiza informações explícitas em texto.', 1, 9, 1, NOW(), NOW()),
    (506, 2, 'Infere o sentido de palavras ou expressões desconhecidas em textos, com base no contexto da frase ou do texto.', 1, 9, 1, NOW(), NOW()),
    (507, 2, 'Infere informações implícitas nos textos lidos.', 1, 9, 1, NOW(), NOW()),
    (508, 2, 'Estabelece relações entre partes de um texto, identificando substituições lexicais (de substantivo por sinônimos) ou pronominais (uso de pronomes anafóricos – pessoais, possessivos, demonstrativos) que contribuem para a continuidade do texto.', 1, 9, 1, NOW(), NOW()),
    (509, 2, 'Escreve palavras com som da letra S, mas grafadas com as letras S, C, X, SS, Z, Ç, SÇ, SC, XC.', 1, 9, 1, NOW(), NOW()),
    (510, 2, 'Produzir, individualmente, notícia.', 1, 9, 1, NOW(), NOW()),
    (511, 2, 'Utilizar adequadamente os sinais de pontuação na escrita de textos.', 1, 9, 1, NOW(), NOW()),
    (512, 2, 'Descreve a localização de pessoas ou objetos no espaço, por meio de mapas e coordenadas geográficas.', 2, 9, 1, NOW(), NOW()),
    (513, 2, 'Calcula adição com números de até 6 ordens, sem e com agrupamento.', 2, 9, 1, NOW(), NOW()),
    (514, 2, 'Calcula subtração com números de até 6 ordens, sem e com desagrupamento.', 2, 9, 1, NOW(), NOW()),
    (515, 2, 'Calcula multiplicação até a centena de milhar no multiplicando e unidade no multiplicador.', 2, 9, 1, NOW(), NOW()),
    (516, 2, 'Lê números fracionários.', 2, 9, 1, NOW(), NOW()),
    (517, 2, 'Escreve números fracionários.', 2, 9, 1, NOW(), NOW()),
    (518, 2, 'Representa frações na reta numérica.', 2, 9, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    updated_at = IF(tipo_avaliacao_id <> VALUES(tipo_avaliacao_id)
        OR NOT (texto <=> VALUES(texto))
        OR componente_curricular_id <> VALUES(componente_curricular_id)
        OR serie_id <> VALUES(serie_id)
        OR status <> VALUES(status), NOW(), updated_at),
    tipo_avaliacao_id = VALUES(tipo_avaliacao_id),
    texto = VALUES(texto),
    componente_curricular_id = VALUES(componente_curricular_id),
    serie_id = VALUES(serie_id),
    status = VALUES(status);

