# Compressão GZIP
gzip on;
gzip_comp_level 6;
gzip_min_length 1024;
gzip_vary on;
gzip_proxied any;

gzip_types
    text/plain
    text/css
    text/javascript
    application/javascript
    application/x-javascript
    application/json
    application/xml
    application/xml+rss
    image/svg+xml
    font/woff
    font/woff2;

server {
    listen 80;
    server_name edu.hubdetestes.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name edu.hubdetestes.online;

    root /var/www/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/edu.hubdetestes.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/edu.hubdetestes.online/privkey.pem;

    # Cache para arquivos estáticos
    location ~* \.(?:css|js|woff2|woff|ttf|eot|svg|png|jpg|jpeg|gif|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        access_log off;

        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # CRÍTICO pro Laravel entender HTTPS
        fastcgi_param HTTPS on;
    }

    location ~ /\.ht {
        deny all;
    }
}