import { MigrationInterface, QueryRunner } from 'typeorm';

// US003/CT01-CT07: cria identidades, catálogos, matrícula e históricos com FKs explícitas.
export class InitialPeopleAndMunicipalServer1760000000000 implements MigrationInterface {
  name = 'InitialPeopleAndMunicipalServer1760000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    const statements = [
      `CREATE TABLE people (uuid CHAR(36) NOT NULL, full_name VARCHAR(200) NOT NULL, cpf CHAR(11) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (uuid), INDEX idx_people_name (full_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE user_accounts (person_uuid CHAR(36) NOT NULL, login_email VARCHAR(320) NOT NULL, status VARCHAR(16) NOT NULL, google_subject VARCHAR(255) NULL, google_display_name VARCHAR(200) NULL, google_photo_url VARCHAR(2048) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (person_uuid), UNIQUE KEY uq_user_google_subject (google_subject), CONSTRAINT fk_user_person FOREIGN KEY (person_uuid) REFERENCES people(uuid), CONSTRAINT ck_user_status CHECK (status IN ('active','inactive'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE municipal_server_profiles (person_uuid CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (person_uuid), CONSTRAINT fk_server_person FOREIGN KEY (person_uuid) REFERENCES people(uuid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE employment_contract_types (id CHAR(36) NOT NULL, code VARCHAR(40) NOT NULL, label VARCHAR(120) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (id), UNIQUE KEY uq_contract_type_code (code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE legal_regimes (id CHAR(36) NOT NULL, code VARCHAR(40) NOT NULL, label VARCHAR(120) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (id), UNIQUE KEY uq_legal_regime_code (code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE jobs (uuid CHAR(36) NOT NULL, name VARCHAR(160) NOT NULL, description TEXT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (uuid), INDEX idx_jobs_name (name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE career_bands (uuid CHAR(36) NOT NULL, job_uuid CHAR(36) NOT NULL, code VARCHAR(40) NOT NULL, label VARCHAR(120) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (uuid), UNIQUE KEY uq_career_band_job_code (job_uuid,code), CONSTRAINT fk_career_band_job FOREIGN KEY (job_uuid) REFERENCES jobs(uuid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE work_locations (uuid CHAR(36) NOT NULL, name VARCHAR(180) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (uuid), INDEX idx_work_locations_name (name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_statuses (code VARCHAR(24) NOT NULL, label VARCHAR(80) NOT NULL, terminal BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY (code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `INSERT INTO matricula_statuses (code,label,terminal) VALUES ('active','Ativo',FALSE),('away','Afastado',FALSE),('exonerated','Exonerado',TRUE)`,
      `CREATE TABLE matriculas (uuid CHAR(36) NOT NULL, server_person_uuid CHAR(36) NOT NULL, registration_number VARCHAR(40) NOT NULL, contract_type_id CHAR(36) NOT NULL, legal_regime_id CHAR(36) NOT NULL, admitted_on DATE NOT NULL, probation_completed_on DATE NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (uuid), UNIQUE KEY uq_matricula_registration (registration_number), INDEX idx_matricula_person (server_person_uuid), CONSTRAINT fk_matricula_server FOREIGN KEY (server_person_uuid) REFERENCES municipal_server_profiles(person_uuid), CONSTRAINT fk_matricula_contract FOREIGN KEY (contract_type_id) REFERENCES employment_contract_types(id), CONSTRAINT fk_matricula_regime FOREIGN KEY (legal_regime_id) REFERENCES legal_regimes(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_status_periods (uuid CHAR(36) NOT NULL, matricula_uuid CHAR(36) NOT NULL, status_code VARCHAR(24) NOT NULL, valid_from DATE NOT NULL, valid_until DATE NULL, reason VARCHAR(500) NULL, PRIMARY KEY (uuid), INDEX idx_matricula_status_timeline (matricula_uuid,valid_from), CONSTRAINT fk_status_period_matricula FOREIGN KEY (matricula_uuid) REFERENCES matriculas(uuid), CONSTRAINT fk_status_period_status FOREIGN KEY (status_code) REFERENCES matricula_statuses(code), CONSTRAINT ck_status_period_dates CHECK (valid_until IS NULL OR valid_until >= valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_job_periods (uuid CHAR(36) NOT NULL, matricula_uuid CHAR(36) NOT NULL, job_uuid CHAR(36) NOT NULL, valid_from DATE NOT NULL, valid_until DATE NULL, PRIMARY KEY (uuid), INDEX idx_matricula_job_timeline (matricula_uuid,valid_from), CONSTRAINT fk_job_period_matricula FOREIGN KEY (matricula_uuid) REFERENCES matriculas(uuid), CONSTRAINT fk_job_period_job FOREIGN KEY (job_uuid) REFERENCES jobs(uuid), CONSTRAINT ck_job_period_dates CHECK (valid_until IS NULL OR valid_until >= valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_location_periods (uuid CHAR(36) NOT NULL, matricula_uuid CHAR(36) NOT NULL, work_location_uuid CHAR(36) NOT NULL, valid_from DATE NOT NULL, valid_until DATE NULL, PRIMARY KEY (uuid), INDEX idx_matricula_location_timeline (matricula_uuid,valid_from), CONSTRAINT fk_location_period_matricula FOREIGN KEY (matricula_uuid) REFERENCES matriculas(uuid), CONSTRAINT fk_location_period_location FOREIGN KEY (work_location_uuid) REFERENCES work_locations(uuid), CONSTRAINT ck_location_period_dates CHECK (valid_until IS NULL OR valid_until >= valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_work_conditions (uuid CHAR(36) NOT NULL, matricula_uuid CHAR(36) NOT NULL, weekly_workload_hours DECIMAL(6,2) NOT NULL, shift_code VARCHAR(40) NOT NULL, valid_from DATE NOT NULL, valid_until DATE NULL, PRIMARY KEY (uuid), INDEX idx_matricula_conditions_timeline (matricula_uuid,valid_from), CONSTRAINT fk_conditions_matricula FOREIGN KEY (matricula_uuid) REFERENCES matriculas(uuid), CONSTRAINT ck_conditions_hours CHECK (weekly_workload_hours > 0), CONSTRAINT ck_conditions_dates CHECK (valid_until IS NULL OR valid_until >= valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
      `CREATE TABLE matricula_career_progressions (uuid CHAR(36) NOT NULL, matricula_uuid CHAR(36) NOT NULL, career_band_uuid CHAR(36) NOT NULL, valid_from DATE NOT NULL, reference_document VARCHAR(180) NULL, PRIMARY KEY (uuid), INDEX idx_matricula_progression_timeline (matricula_uuid,valid_from), CONSTRAINT fk_progression_matricula FOREIGN KEY (matricula_uuid) REFERENCES matriculas(uuid), CONSTRAINT fk_progression_band FOREIGN KEY (career_band_uuid) REFERENCES career_bands(uuid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    ];
    for (const statement of statements) await queryRunner.query(statement);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const tables = ['matricula_career_progressions','matricula_work_conditions','matricula_location_periods','matricula_job_periods','matricula_status_periods','matriculas','matricula_statuses','work_locations','career_bands','jobs','legal_regimes','employment_contract_types','municipal_server_profiles','user_accounts','people'];
    for (const table of tables) await queryRunner.query(`DROP TABLE ${table}`);
  }
}
